<?php
declare(strict_types=1);
if(function_exists('header_remove'))header_remove('X-Powered-By');
$root=dirname(__DIR__);$configPath=trim((string)(getenv('SOKNA_PUBLIC_CONFIG')?:($root.'/config.php')));
require_once $root.'/src/Core/Config.php';require_once $root.'/src/Core/Database.php';require_once $root.'/src/Emergency/PublicUpdateException.php';require_once $root.'/src/Emergency/EmergencyAccessService.php';require_once $root.'/src/Emergency/PairingSecretStore.php';require_once $root.'/src/Emergency/PublicTakeoverService.php';require_once $root.'/src/Emergency/PublicUpdateService.php';
use Sokna\PublicEdge\Core\Config;use Sokna\PublicEdge\Core\Database;use Sokna\PublicEdge\Emergency\EmergencyAccessService;use Sokna\PublicEdge\Emergency\PairingSecretStore;use Sokna\PublicEdge\Emergency\PublicTakeoverService;use Sokna\PublicEdge\Emergency\PublicUpdateService;use Sokna\PublicEdge\Emergency\PublicUpdateException;
header('Cache-Control: no-store, max-age=0');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header("Content-Security-Policy: default-src 'self'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
function g33_json(array $v,int $status=200): never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function g33_basic_code(): string{$h=(string)($_SERVER['HTTP_AUTHORIZATION']??'');if(stripos($h,'Basic ')!==0)return '';$raw=base64_decode(substr($h,6),true);if(!is_string($raw))return '';[, $pass]=array_pad(explode(':',$raw,2),2,'');return $pass;}
try{
 if(!is_file($configPath)){http_response_code(503);echo 'Public not configured';exit;}$cfgRaw=require $configPath;if(!is_array($cfgRaw))throw new RuntimeException('invalid config');$cfg=Config::fromArray($cfgRaw);$storage=trim($cfg->string('app.storage_dir'));if($storage==='')$storage=$root.'/storage';$access=new EmergencyAccessService($storage);$updates=new PublicUpdateService($root,$storage,$root.'/resources/update-trust-v1.json',function()use($cfg):bool{try{return (int)Database::connect($cfg)->query('SELECT 1')->fetchColumn()===1;}catch(Throwable){return false;}});
 $action=(string)($_GET['action']??'');
 if($action==='reenroll'&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'){$body=json_decode((string)file_get_contents('php://input'),true);if(!is_array($body))g33_json(['ok'=>false,'error'=>'invalid_json'],400);$pdo=Database::connect($cfg);$store=new PairingSecretStore($pdo,$cfg->requiredString('relay.secret_encryption_key_base64'));$svc=new PublicTakeoverService($pdo,$store,$access);try{g33_json($svc->complete((string)($body['new_installation_id']??''),(string)($body['enrollment_code']??''),(string)($body['new_shared_secret']??''),(string)($body['display_name']??'')));}catch(PublicUpdateException $e){g33_json(['ok'=>false,'error'=>$e->errorCode],$e->httpStatus);}}
 if(!$access->configured()){http_response_code(503);echo 'Emergency access is not provisioned.';exit;}$code=g33_basic_code();if(!$access->verify($code)){header('WWW-Authenticate: Basic realm="SOKNA Public Emergency", charset="UTF-8"');http_response_code(401);echo 'Emergency authentication required.';exit;}
 $pdo=null;$db='unavailable';try{$pdo=Database::connect($cfg);$db=(int)$pdo->query('SELECT 1')->fetchColumn()===1?'ready':'unavailable';}catch(Throwable){}
 $notice='';$error='';if(($_SERVER['REQUEST_METHOD']??'GET')==='POST')try{
   if($action==='stage'){if(!isset($_FILES['package'])||!is_uploaded_file($_FILES['package']['tmp_name']))throw new PublicUpdateException('upload_missing','Update package is required.');$st=$updates->stageUploadedZip($_FILES['package']['tmp_name'],'emergency');$access->audit('update_stage',null,'emergency',['version'=>$st['version']]);$notice='Package verified and staged.';}
   elseif($action==='activate'){$updates->activateStaged('emergency');$access->audit('update_activate',null,'emergency',[]);$notice='Staged Public version activated.';}
   elseif($action==='repair'){$updates->repairStaged('emergency');$access->audit('update_repair',null,'emergency',[]);$notice='Public version repaired.';}
   elseif($action==='rollback'){$updates->rollback('emergency');$access->audit('update_rollback',null,'emergency',[]);$notice='Public rolled back to LKG.';}
   elseif($action==='kill_switch'){if(!$pdo)throw new PublicUpdateException('database_unavailable','Database unavailable.',503);$store=new PairingSecretStore($pdo,$cfg->requiredString('relay.secret_encryption_key_base64'));$svc=new PublicTakeoverService($pdo,$store,$access);$svc->killSwitch((string)($_POST['installation_id']??''));$notice='Remote/order intake disabled.';}
   elseif($action==='takeover_offer'){if(!$pdo)throw new PublicUpdateException('database_unavailable','Database unavailable.',503);$store=new PairingSecretStore($pdo,$cfg->requiredString('relay.secret_encryption_key_base64'));$svc=new PublicTakeoverService($pdo,$store,$access);$offer=$svc->createOffer((string)($_POST['old_installation_id']??''),(string)($_POST['new_installation_id']??''));$notice='Enrollment code (shown once): '.$offer['enrollment_code'];}
 }catch(PublicUpdateException $e){$error=$e->errorCode;}catch(Throwable){$error='emergency_action_failed';}
 $snap=$updates->snapshot();$logs=$access->recentAudit(60);
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SOKNA Public Emergency</title><style>body{font-family:system-ui,sans-serif;background:#111;color:#eee;max-width:980px;margin:auto;padding:24px}section{border:1px solid #444;border-radius:14px;padding:18px;margin:16px 0}input,button{font:inherit;padding:10px;margin:4px}button{cursor:pointer}.ok{background:#173d2b}.err{background:#4b1d1d}code,pre{direction:ltr;text-align:left;white-space:pre-wrap}</style></head><body><h1>Public Emergency Console</h1><p>Break-glass only · DB: <strong><?=htmlspecialchars($db)?></strong> · version: <strong><?=htmlspecialchars($snap['current_version'])?></strong></p><?php if($notice):?><p class="ok"><?=htmlspecialchars($notice)?></p><?php endif;if($error):?><p class="err"><?=htmlspecialchars($error)?></p><?php endif;?><section><h2>Update / Recovery</h2><pre><?=htmlspecialchars(json_encode($snap,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre><form method="post" action="?action=stage" enctype="multipart/form-data"><input type="file" name="package" accept=".zip" required><button>Verify + Stage</button></form><form method="post" action="?action=activate"><button>Activate</button></form><form method="post" action="?action=repair"><button>Repair same version</button></form><form method="post" action="?action=rollback"><button>Rollback LKG</button></form></section><section><h2>Kill switch / Takeover</h2><form method="post" action="?action=kill_switch"><input name="installation_id" placeholder="installation id" required><button>Disable remote intake</button></form><form method="post" action="?action=takeover_offer"><input name="old_installation_id" placeholder="old installation A" required><input name="new_installation_id" placeholder="new installation B" required><button>Create one-time re-enrollment code</button></form></section><section><h2>Limited audit log</h2><pre><?=htmlspecialchars(json_encode($logs,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></section></body></html><?php
}catch(Throwable){http_response_code(500);echo 'Emergency console unavailable.';}
