<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAny($core,['cashier_accounts']);$csrf=WebAction::csrfToken();$isAdmin=(string)($user['role']??'')==='admin';
ProductShell::start($core,$user,'مالی و تسویه','finance','حساب‌های باز، رسیدها، دوره‌های مالی و تنظیمات مالیات را یک‌جا مدیریت کن.',true);
?>
<section class="sc-workspace" data-finance-workspace data-api="finance/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>" data-admin="<?= $isAdmin?'1':'0' ?>">
  <div class="sc-toolbar sc-local-nav"><div class="sc-tabs" role="tablist" aria-label="مالی"><button class="sc-tab" role="tab" aria-selected="true" type="button" data-tab="accounts">تسویه</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="receipts">فاکتورها</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="periods">دوره‌ها</button><?php if($isAdmin): ?><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="tax">مالیات</button><?php endif; ?></div><button class="sc-button sc-button--secondary" type="button" data-refresh>تازه‌سازی</button></div>
  <div class="sc-summary-grid sc-finance-summary" aria-label="خلاصه مالی"><article class="sc-card sc-metric"><span>حساب باز</span><strong data-metric="accounts">—</strong><small>قابل بررسی برای تسویه</small></article><article class="sc-card sc-metric"><span>فاکتور اخیر</span><strong data-metric="invoices">—</strong><small>در آرشیو سریع مالی</small></article><article class="sc-card sc-metric"><span>مطالبات مشتریان</span><strong data-metric="receivables">—</strong><small>مانده حساب مشتریان</small></article><article class="sc-card sc-metric"><span>مالیات</span><strong data-metric="tax">—</strong><small>وضعیت و نرخ جاری</small></article></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال دریافت وضعیت مالی…</div>
  <section class="sc-work-panel" data-panel="accounts"><div class="sc-section-head"><div><h2>حساب‌های باز</h2><p>یک حساب را انتخاب کن؛ جزئیات و اقدام‌های تسویه کنار همان فهرست باز می‌شوند.</p></div></div><div class="sc-finance-account-layout"><div class="sc-finance-account-list" data-account-list></div><aside class="sc-card sc-finance-account-detail sc-hidden" data-account-detail aria-live="polite"></aside></div></section>
  <section class="sc-work-panel sc-data-panel sc-finance-invoice-panel" data-panel="receipts" hidden>
    <div class="sc-section-head"><div><h2>فاکتورها</h2><p>آخرین اسناد تسویه را جست‌وجو کن و جزئیات کامل هر سند را همان‌جا ببین.</p></div><span class="sc-badge" data-invoice-count>—</span></div>
    <div class="sc-toolbar sc-finance-invoice-toolbar" aria-label="فیلتر فاکتورها">
      <label class="sc-field sc-grow"><span class="sc-visually-hidden">جست‌وجوی فاکتور</span><input class="sc-control" type="search" data-invoice-search placeholder="جست‌وجوی شماره فاکتور، میز یا ثبت‌کننده…" autocomplete="off"></label>
      <label class="sc-field"><span class="sc-visually-hidden">مقصد تسویه</span><select class="sc-control" data-invoice-destination><option value="">همه مقصدها</option><option value="direct">پرداخت مستقیم</option><option value="subscriber">حساب مشتری</option><option value="accommodation">اقامتگاه</option></select></label>
      <label class="sc-field"><span class="sc-visually-hidden">وضعیت فاکتور</span><select class="sc-control" data-invoice-status><option value="">همه وضعیت‌ها</option><option value="completed">ثبت‌شده</option><option value="reversal">سند برگشت</option></select></label>
      <button class="sc-button sc-button--secondary" type="button" data-invoice-reset>پاک‌کردن فیلتر</button>
    </div>
    <div class="sc-finance-invoice-layout">
      <div class="sc-finance-invoice-list" data-receipt-list></div>
      <aside class="sc-card sc-finance-invoice-detail sc-hidden" data-invoice-detail aria-live="polite"></aside>
    </div>
  </section>
  <section class="sc-work-panel" data-panel="periods" hidden><div class="sc-section-head"><div><h2>دوره‌های مالی</h2><p>در این بخش می‌توان وضعیت و جمع‌بندی دوره‌های مالی را بررسی کرد.</p></div></div><div class="sc-stack" data-period-list></div></section>
  <?php if($isAdmin): ?><section class="sc-work-panel" data-panel="tax" hidden><div class="sc-section-head"><div><h2>مالیات</h2><p>تغییر نرخ فقط روی محاسبات بعد از زمان شروع آن اثر می‌گذارد.</p></div></div><div class="sc-grid"><article class="sc-card"><div class="sc-card__body sc-stack"><h3>وضعیت و نرخ پیش‌فرض</h3><label class="sc-field"><span class="sc-field__label">نرخ جدید، درصد</span><input class="sc-control" inputmode="decimal" data-tax-rate placeholder="مثلاً ۱۰"></label><label class="sc-field"><span class="sc-field__label">زمان شروع</span><input class="sc-control" type="datetime-local" data-tax-effective></label><div class="sc-actions"><button class="sc-button" type="button" data-save-tax-rate>ثبت نرخ</button><button class="sc-button sc-button--secondary" type="button" data-toggle-tax>تغییر وضعیت مالیات</button></div></div></article><article class="sc-card"><div class="sc-card__body sc-stack"><h3>قانون مالیات کالا</h3><label class="sc-field"><span class="sc-field__label">آیتم</span><select class="sc-control" data-tax-item></select></label><label class="sc-field"><span class="sc-field__label">نوع قانون</span><select class="sc-control" data-tax-policy><option value="inherit_default">نرخ پیش‌فرض</option><option value="exempt">معاف</option><option value="custom_rate">نرخ اختصاصی</option></select></label><label class="sc-field"><span class="sc-field__label">نرخ اختصاصی، درصد</span><input class="sc-control" inputmode="decimal" data-tax-custom placeholder="مثلاً ۱۰"></label><label class="sc-field"><span class="sc-field__label">زمان شروع</span><input class="sc-control" type="datetime-local" data-tax-policy-effective></label><button class="sc-button" type="button" data-save-tax-policy>ثبت قانون</button></div></article></div><div class="sc-stack" data-tax-history></div></section><?php endif; ?>
</section>
<script src="<?=ProductShell::asset('assets/finance-workspace.js')?>" defer></script>
<?php ProductShell::end(); ?>
