<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAny($core,['cashier_accounts']);$csrf=WebAction::csrfToken();$isAdmin=(string)($user['role']??'')==='admin';
ProductShell::start($core,$user,'مالی و تسویه','finance','حساب‌های باز، رسیدها، دوره‌های مالی و مالیات از ownerهای canonical نمایش داده می‌شوند.');
?>
<section class="sc-workspace" data-finance-workspace data-api="/finance/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>" data-admin="<?= $isAdmin?'1':'0' ?>">
  <div class="sc-summary-grid" aria-label="خلاصه مالی"><article class="sc-card sc-metric"><span>حساب باز</span><strong data-metric="accounts">—</strong><small>قابل بررسی برای تسویه</small></article><article class="sc-card sc-metric"><span>مطالبات مشتریان</span><strong data-metric="receivables">—</strong><small>مانده حساب مشتریان</small></article><article class="sc-card sc-metric"><span>مالیات</span><strong data-metric="tax">—</strong><small>وضعیت ماژول و نرخ جاری</small></article></div>
  <div class="sc-toolbar"><div class="sc-tabs" role="tablist" aria-label="مالی"><button class="sc-tab" role="tab" aria-selected="true" type="button" data-tab="accounts">تسویه</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="receipts">رسیدها</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="periods">دوره‌ها</button><?php if($isAdmin): ?><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="tax">مالیات</button><?php endif; ?></div><button class="sc-button sc-button--secondary" type="button" data-refresh>تازه‌سازی</button></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال دریافت وضعیت مالی…</div>
  <section class="sc-work-panel" data-panel="accounts"><div class="sc-section-head"><div><h2>حساب‌های باز</h2><p>تسویه فقط روی حساب تأییدشده و با signature فعلی انجام می‌شود.</p></div></div><div class="sc-card-grid" data-account-list></div><div class="sc-card sc-hidden" data-account-detail></div></section>
  <section class="sc-work-panel" data-panel="receipts" hidden><div class="sc-section-head"><div><h2>رسیدهای اخیر</h2><p>سندهای completed/reversal حذف یا بازنویسی نمی‌شوند.</p></div></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>شماره</th><th>میز</th><th>مقصد</th><th>مبلغ</th><th>وضعیت</th><th></th></tr></thead><tbody data-receipt-list></tbody></table></div></section>
  <section class="sc-work-panel" data-panel="periods" hidden><div class="sc-section-head"><div><h2>دوره‌های مالی</h2><p>بستن نهایی دوره تا اتصال کنترل Public/Deferred در G2/G3 فقط به‌صورت مشاهده‌ای است.</p></div></div><div class="sc-stack" data-period-list></div></section>
  <?php if($isAdmin): ?><section class="sc-work-panel" data-panel="tax" hidden><div class="sc-section-head"><div><h2>مالیات</h2><p>تغییرات versioned هستند و روی اسناد قبلی اثر نمی‌گذارند.</p></div></div><div class="sc-grid"><article class="sc-card"><div class="sc-card__body sc-stack"><h3>وضعیت و نرخ پیش‌فرض</h3><label class="sc-field"><span class="sc-field__label">نرخ جدید، درصد</span><input class="sc-control" inputmode="decimal" data-tax-rate placeholder="مثلاً ۱۰"></label><label class="sc-field"><span class="sc-field__label">زمان شروع</span><input class="sc-control" type="datetime-local" data-tax-effective></label><div class="sc-actions"><button class="sc-button" type="button" data-save-tax-rate>ثبت نسخه نرخ</button><button class="sc-button sc-button--secondary" type="button" data-toggle-tax>تغییر وضعیت مالیات</button></div></div></article><article class="sc-card"><div class="sc-card__body sc-stack"><h3>سیاست کالا</h3><select class="sc-control" data-tax-item></select><select class="sc-control" data-tax-policy><option value="inherit_default">نرخ پیش‌فرض</option><option value="exempt">معاف</option><option value="custom_rate">نرخ اختصاصی</option></select><input class="sc-control" inputmode="decimal" data-tax-custom placeholder="نرخ اختصاصی درصد"><input class="sc-control" type="datetime-local" data-tax-policy-effective><button class="sc-button" type="button" data-save-tax-policy>ثبت سیاست</button></div></article></div><div class="sc-stack" data-tax-history></div></section><?php endif; ?>
</section>
<script src="/assets/finance-workspace.js" defer></script>
<?php ProductShell::end(); ?>
