<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/apps/local-web/bootstrap.php';
use Sokna\Local\Domain\Reporting\ReportingException;
function g43(bool $ok,string $m): void{if(!$ok)throw new RuntimeException($m);}
$host=(string)(getenv('SOKNA_TEST_DB_HOST')?:'127.0.0.1');$port=(string)(getenv('SOKNA_TEST_DB_PORT')?:'3306');$db=(string)(getenv('SOKNA_TEST_DB_NAME')?:'sokna_m2');$u=(string)(getenv('SOKNA_TEST_DB_USER')?:'sokna');$pw=(string)(getenv('SOKNA_TEST_DB_PASS')?:'sokna');$data=sys_get_temp_dir().'/sokna-g43-'.bin2hex(random_bytes(4));@mkdir($data,0700,true);
$core=sokna_local_bootstrap(['app'=>['timezone'=>'UTC','data_dir'=>$data],'db'=>['host'=>$host,'port'=>$port,'name'=>$db,'charset'=>'utf8mb4','user'=>$u,'pass'=>$pw],'installation'=>['id'=>'g43-installation'],'runtime'=>['local_token'=>'g43'],'public'=>['base_url'=>'','shared_secret'=>''],'integrations'=>['accommodation'=>['base_url'=>'','secret'=>'']]]);
$applied=$core->migrations()->migrate();g43(in_array('0024_g4_business_extensions',$applied,true),'G4.3 migration missing');$pdo=$core->database();foreach(['marketing_campaigns','marketing_events','notification_preferences','notification_push_subscriptions','notification_outbox','notification_inbox'] as $t){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$t]);g43((int)$q->fetchColumn()===1,"missing {$t}");}
$hash=password_hash('G43AdminPass!',PASSWORD_DEFAULT);$pdo->prepare('INSERT INTO users(username,password_hash,display_name,role,active) VALUES(?,?,?,?,1)')->execute(['g43-admin',$hash,'G43 Admin','admin']);$adminId=(int)$pdo->lastInsertId();$admin=['id'=>$adminId,'username'=>'g43-admin','display_name'=>'G43 Admin','role'=>'admin','active'=>1];$pdo->prepare('INSERT INTO users(username,password_hash,display_name,role,active) VALUES(?,?,?,?,1)')->execute(['g43-operator',$hash,'G43 Operator','operator']);$operatorId=(int)$pdo->lastInsertId();
$now=gmdate('Y-m-d\TH:i');$later=gmdate('Y-m-d\TH:i',time()+3600);$c=$core->marketing()->saveCampaign(['name'=>'G43 Campaign','headline'=>'کمپین G43','body'=>'متن کمپین','status'=>'active','public_visible'=>true,'starts_at'=>$now,'ends_at'=>$later],$admin);g43((int)$c['id']>0,'campaign save failed');$e=$core->marketing()->saveEvent(['title'=>'رویداد G43','description'=>'تست','status'=>'scheduled','public_visible'=>true,'starts_at'=>$now,'ends_at'=>$later,'capacity'=>20,'location_label'=>'سکنا'],$admin);g43((int)$e['id']>0,'event save failed');$feed=$core->marketing()->publicFeed();g43(count($feed['campaigns'])===1&&count($feed['events'])===1,'public marketing feed failed');
$report=$core->reporting()->report(gmdate('Y-m-d'),gmdate('Y-m-d'));g43(isset($report['summary']['net_sales'])&&isset($report['daily']),'report shape invalid');$bounded=false;try{$core->reporting()->report('2020-01-01','2022-01-01');}catch(ReportingException $x){$bounded=$x->errorCode==='range_too_large';}g43($bounded,'report range is not bounded');
$core->notifications()->savePreferences(['in_app_enabled'=>true,'push_enabled'=>false],$admin);$queued=$core->notifications()->compose(['title'=>'اعلان G43','body'=>'پیام تست','target_url'=>'/reports/','role'=>''],$admin);g43((int)$queued['recipients']===2&&((int)$queued['queued'])>=2,'notification compose failed');$processed=$core->notifications()->processPending(20);g43((int)$processed['delivered']>=2,'in-app outbox worker failed');$snap=$core->notifications()->snapshot($admin);g43((int)$snap['unread']>=1,'notification inbox missing');
$core->notifications()->savePreferences(['in_app_enabled'=>true,'push_enabled'=>true],$admin);$reg=$core->notifications()->registerPush(['endpoint'=>'https://push.example.invalid/g43','keys'=>['p256dh'=>'key-g43','auth'=>'auth-g43']],$admin);g43(($reg['registered']??false)===true,'push subscription registry failed');$core->notifications()->queueForUser($adminId,'g43.push.test','Push G43','بدون bridge باید skip شود','/notifications/');$push=$core->notifications()->processPending(20);g43((int)$push['skipped']>=1,'unconfigured push bridge was not safely skipped');
$guest=$core->publicProjectionBuilder()->guestPublish();g43(isset($guest['snapshot']['marketing'])&&count($guest['snapshot']['marketing']['campaigns'])===1,'marketing missing from guest publish');$models=$core->publicProjectionBuilder()->remoteModels();$keys=array_column($models,'model_key');g43(in_array('reports',$keys,true)&&in_array('notifications',$keys,true),'remote report/notification models missing');
fwrite(STDOUT,"G4.3 Business Extensions MariaDB E2E: OK\n");
