<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/apps/local-web/bootstrap.php';
use Sokna\Local\Domain\Printing\PrintException;
function g44db(bool $ok,string $m): void{if(!$ok)throw new RuntimeException($m);}
$host=(string)(getenv('SOKNA_TEST_DB_HOST')?:'127.0.0.1');$port=(string)(getenv('SOKNA_TEST_DB_PORT')?:'3306');$db=(string)(getenv('SOKNA_TEST_DB_NAME')?:'sokna_m2');$u=(string)(getenv('SOKNA_TEST_DB_USER')?:'sokna');$pw=(string)(getenv('SOKNA_TEST_DB_PASS')?:'sokna');$data=sys_get_temp_dir().'/sokna-g44-'.bin2hex(random_bytes(4));@mkdir($data,0700,true);
$core=sokna_local_bootstrap(['app'=>['timezone'=>'UTC','data_dir'=>$data],'db'=>['host'=>$host,'port'=>$port,'name'=>$db,'charset'=>'utf8mb4','user'=>$u,'pass'=>$pw],'installation'=>['id'=>'g44-installation'],'runtime'=>['local_token'=>'g44'],'public'=>['base_url'=>'','shared_secret'=>''],'integrations'=>['accommodation'=>['base_url'=>'','secret'=>'']]]);
$core->migrations()->migrate();$pdo=$core->database();$mq=$pdo->prepare('SELECT COUNT(*) FROM schema_migrations WHERE migration=?');$mq->execute(['0025_g4_print_template_packages']);g44db((int)$mq->fetchColumn()===1,'G4.4 migration missing');
foreach(['print_template_packages','print_template_activations'] as $t){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$t]);g44db((int)$q->fetchColumn()===1,"missing {$t}");}
$hash=password_hash('G44AdminPass!',PASSWORD_DEFAULT);$pdo->prepare('INSERT INTO users(username,password_hash,display_name,role,active) VALUES(?,?,?,?,1)')->execute(['g44-admin',$hash,'G44 Admin','admin']);$admin=['id'=>(int)$pdo->lastInsertId(),'username'=>'g44-admin','display_name'=>'G44 Admin','role'=>'admin','active'=>1];
$customer=file_get_contents(dirname(__DIR__).'/docs/examples/print-templates/customer-clean-1.0.0.soknaprint');$prep=file_get_contents(dirname(__DIR__).'/docs/examples/print-templates/preparation-clear-1.0.0.soknaprint');g44db(is_string($customer)&&is_string($prep),'package fixtures missing');
$c=$core->printTemplates()->import($customer,$admin);$p=$core->printTemplates()->import($prep,$admin);g44db((int)$c['package_id']>0&&(int)$p['package_id']>0,'package import failed');$again=$core->printTemplates()->import($customer,$admin);g44db(($again['deduplicated']??false)===true&&(int)$again['package_id']===(int)$c['package_id'],'package dedupe failed');
$core->printTemplates()->activate((int)$c['package_id'],$admin);$core->printTemplates()->activate((int)$p['package_id'],$admin);$snap=$core->printTemplates()->snapshot();g44db(isset($snap['active']['customer'],$snap['active']['preparation']),'activation snapshot missing');
$conf=json_decode($customer,true,32,JSON_THROW_ON_ERROR);$conf['name']='نسخه متعارض';$blocked=false;try{$core->printTemplates()->import(json_encode($conf,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$admin);}catch(PrintException $e){$blocked=$e->errorCode==='print_template_version_conflict';}g44db($blocked,'immutable version conflict not blocked');
$agent=$core->printing()->createAgent('G44 Agent',$admin);$auth=$core->printing()->authenticate('Bearer '.$agent['token']);$core->printing()->heartbeat($auth,['hostname'=>'g44','agent_version'=>'6.2.5','os_version'=>'Windows','printers'=>[['name'=>'G44 Queue']],'health'=>[],'bridge_protocol_version'=>1,'bridge_port'=>17653,'bridge_pairing_id'=>str_repeat('a',48),'bridge_origin'=>'http://127.0.0.1:8080']);
$core->printing()->configureDestination('customer_receipt',['agent_id'=>$agent['agent_id'],'windows_queue_name'=>'G44 Queue','active'=>true,'copies'=>1,'paper_width_mm'=>80,'printable_width_mm'=>72.1],$admin);$core->printing()->configureDestination('prep_shared',['agent_id'=>$agent['agent_id'],'windows_queue_name'=>'G44 Queue','active'=>true,'copies'=>1,'paper_width_mm'=>80,'printable_width_mm'=>72.1],$admin);
$job=$core->printing()->enqueueTest('customer_receipt','g44-test-0001',$admin,(int)$c['package_id']);g44db((int)$job['job_id']>0,'template test job not queued');$q=$pdo->prepare('SELECT payload_json FROM print_jobs WHERE id=?');$q->execute([(int)$job['job_id']]);$payload=json_decode((string)$q->fetchColumn(),true);g44db(($payload['schema']??'')==='sokna-print-document-v2'&&($payload['template']['design']['item_layout']??'')==='responsive-receipt','selected template not fenced into print payload');
$preview=$core->printTemplates()->preview((int)$c['package_id'],'customer_receipt',$admin);g44db(($preview['preview']['type']??'')==='print.preview'&&($preview['bridge']['pairing_id']??'')===str_repeat('a',48),'preview bridge request not built');g44db(($preview['preview']['payload_json']??'')!==''&&str_contains((string)$preview['preview']['payload_json'],'customer-clean')===false,'preview payload unexpectedly carries package executable metadata');
$mgmt=$core->printManagement()->snapshot();g44db(!array_key_exists('bridge_pairing_id',$mgmt['agents'][0]??[]),'pairing material leaked in routine snapshot');
echo "G4.4 Print Template MariaDB E2E: OK\n";
