<?php
declare(strict_types=1);
if(!class_exists(ZipArchive::class)){fwrite(STDERR,"G2.3 lifecycle qualification requires PHP zip.\n");exit(3);}require_once dirname(__DIR__).'/apps/local-web/src/Core/Observability.php';require_once dirname(__DIR__).'/apps/local-web/src/Domain/Update/LocalUpdateException.php';require_once dirname(__DIR__).'/apps/local-web/src/Domain/Update/LocalUpdateService.php';
use Sokna\Local\Core\Observability;use Sokna\Local\Domain\Update\LocalUpdateService;use Sokna\Local\Domain\Update\LocalUpdateException;
function a23(bool $ok,string $m):void{if(!$ok){fwrite(STDERR,"FAIL $m\n");exit(1);}}function rrmdir(string $p):void{if(!file_exists($p))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($p,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}rmdir($p);}function pkg(string $zip,string $version,array $files,array $contracts=['runtime_contract'=>'1.0.0','print_server_protocol'=>4],?array $signature=null):void{$z=new ZipArchive();$z->open($zip,ZipArchive::CREATE|ZipArchive::OVERWRITE);$rows=[];foreach($files as $path=>$content){$rows[]=['path'=>$path,'size'=>strlen($content),'sha256'=>hash('sha256',$content)];$z->addFromString('payload/'.$path,$content);}usort($rows,fn($a,$b)=>strcmp($a['path'],$b['path']));$m=['format'=>'sokna-component-package-v1','schema_version'=>1,'component'=>'local','version'=>$version,'source_commit'=>str_repeat('a',40),'contracts'=>$contracts,'files'=>$rows];$raw=json_encode($m,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";$z->addFromString('manifest.json',$raw);if($signature!==null)$z->addFromString('signature.json',json_encode($signature));$z->close();}
$tmp=sys_get_temp_dir().'/sokna-g23-full-'.bin2hex(random_bytes(5));@mkdir($tmp.'/pkg',0700,true);@mkdir($tmp.'/local/public',0700,true);@mkdir($tmp.'/data',0700,true);file_put_contents($tmp.'/pkg/VERSION.txt','3.0.0');$old=['bootstrap.php'=>'<?php // old','public/_app.php'=>'<?php // old','public/index.php'=>'<?php echo "old";','public/local-recovery.php'=>'<?php echo "stable";','old-only.txt'=>'old'];foreach($old as $p=>$c){@mkdir(dirname($tmp.'/local/'.$p),0700,true);file_put_contents($tmp.'/local/'.$p,$c);}file_put_contents($tmp.'/compat.json',json_encode(['components'=>['local'=>['requires'=>['runtime_contract'=>'>=1.0.0 <2.0.0','print_server_protocol'=>4]]]]));file_put_contents($tmp.'/trust.json',json_encode(['signature_policy'=>'optional_until_release_qualification','ed25519_public_keys'=>[]]));$svc=new LocalUpdateService(new Observability($tmp.'/data'),$tmp.'/pkg',$tmp.'/local',$tmp.'/compat.json',$tmp.'/trust.json');
$new=['bootstrap.php'=>'<?php // new','public/_app.php'=>'<?php // new','public/index.php'=>'<?php echo "new";','new-only.txt'=>'new'];pkg($tmp.'/u.zip','3.1.0',$new);$st=$svc->stageUploadedZip($tmp.'/u.zip',1);a23($st['version']==='3.1.0','stage version');$after=$svc->activateStaged(1);a23($after['active_version']==='3.1.0','activate version');a23(trim((string)file_get_contents($tmp.'/local/new-only.txt'))==='new','new payload');a23(!is_file($tmp.'/local/old-only.txt'),'old-only removed');a23(str_contains((string)file_get_contents($tmp.'/local/public/local-recovery.php'),'stable'),'stable recovery preserved');$back=$svc->rollback(1);a23($back['active_version']==='3.0.0','rollback version');a23(is_file($tmp.'/local/old-only.txt')&&!is_file($tmp.'/local/new-only.txt'),'rollback file set');
$svc->stageUploadedZip($tmp.'/u.zip',1);$svc->activateStaged(1);$svc->stageUploadedZip($tmp.'/u.zip',1);$svc->repairStaged(1);a23($svc->snapshot()['active_version']==='3.1.0','same-version repair');
$bad=['bootstrap.php'=>'<?php // broken','public/_app.php'=>'<?php // broken'];pkg($tmp.'/badhealth.zip','3.2.0',$bad);$svc->stageUploadedZip($tmp.'/badhealth.zip',1);try{$svc->activateStaged(1);a23(false,'broken activation accepted');}catch(LocalUpdateException $e){a23($e->errorCode==='activation_failed','activation failure code');}a23($svc->snapshot()['active_version']==='3.1.0','auto rollback retained active version');a23(is_file($tmp.'/local/public/index.php'),'auto rollback restored entrypoint');
$z=new ZipArchive();$z->open($tmp.'/u.zip');$raw=$z->getFromName('manifest.json');$z->close();$m=json_decode($raw,true);$m['files'][0]['sha256']=str_repeat('0',64);$z=new ZipArchive();$z->open($tmp.'/tamper.zip',ZipArchive::CREATE|ZipArchive::OVERWRITE);foreach($new as $p=>$c)$z->addFromString('payload/'.$p,$c);$z->addFromString('manifest.json',json_encode($m));$z->close();try{$svc->stageUploadedZip($tmp.'/tamper.zip',1);a23(false,'tampered hash accepted');}catch(LocalUpdateException $e){a23($e->errorCode==='hash_mismatch','hash mismatch fail closed');}
echo "G2.3 Local update lifecycle self-test: OK\n";
