<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/apps/local-web/src/Core/Config.php';
require_once dirname(__DIR__).'/apps/local-web/src/Domain/PublicEdge/PublicEdgeSyncException.php';
require_once dirname(__DIR__).'/apps/local-web/src/Domain/PublicEdge/PublicEdgeSyncClient.php';
require_once dirname(__DIR__).'/apps/local-web/src/Domain/PublicEdge/PublicReenrollmentService.php';
use Sokna\Local\Core\Config;use Sokna\Local\Domain\PublicEdge\PublicEdgeSyncClient;use Sokna\Local\Domain\PublicEdge\PublicReenrollmentService;
function g33r(bool $v,string $m):void{if(!$v){fwrite(STDERR,"FAIL $m\n");exit(1);}}
$tmp=sys_get_temp_dir().'/sokna-g33-reenroll-'.bin2hex(random_bytes(4));@mkdir($tmp,0700,true);$configPath=$tmp.'/config.php';$raw=['installation'=>['id'=>'new-B'],'public'=>['base_url'=>'','shared_secret'=>'']];file_put_contents($configPath,"<?php return ".var_export($raw,true).";\n");$seen=[];$cfg=Config::fromArray($raw);$client=new PublicEdgeSyncClient($cfg,function(string $url,string $method,array $headers,string $body)use(&$seen){$seen=compact('url','method','headers','body');return ['status'=>200,'body'=>json_encode(['ok'=>true,'old_installation_id'=>'old-A','new_installation_id'=>'new-B','old_revoked'=>true])];});$svc=new PublicReenrollmentService($cfg,$client,$configPath);$r=$svc->complete('http://127.0.0.1:9999','ONE-TIME-CODE','Cafe B',7);g33r(($r['ok']??false)===true,'reenroll result failed');$saved=require $configPath;g33r((string)$saved['public']['base_url']==='http://127.0.0.1:9999','base url not persisted');g33r(strlen((string)$saved['public']['shared_secret'])===64,'fresh shared secret not persisted');$body=json_decode((string)$seen['body'],true);g33r(($body['new_installation_id']??'')==='new-B','fresh installation id missing');g33r(($body['enrollment_code']??'')==='ONE-TIME-CODE','enrollment code missing');g33r(($body['new_shared_secret']??'')===$saved['public']['shared_secret'],'Public and Local pairing secrets diverged');echo "G3.3 Local re-enrollment pure self-test: OK\n";
