<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/apps/local-web/bootstrap.php';
use Sokna\Local\Domain\Printing\PrintException;
function m8f(string $m):never{fwrite(STDERR,$m.PHP_EOL);exit(1);} function m8a(bool $c,string $m):void{if(!$c)m8f($m);}
$dataRoot=sys_get_temp_dir().'/sokna-m8-'.bin2hex(random_bytes(3));
$core=sokna_local_bootstrap(['app'=>['timezone'=>'Asia/Tehran','data_dir'=>$dataRoot],'runtime'=>['local_base_url'=>'http://127.0.0.1:18080/','local_token'=>str_repeat('l',64)],'db'=>['host'=>(string)(getenv('SOKNA_TEST_DB_HOST')?:'127.0.0.1'),'port'=>(string)(getenv('SOKNA_TEST_DB_PORT')?:'3306'),'name'=>(string)(getenv('SOKNA_TEST_DB_NAME')?:'sokna_m2'),'charset'=>'utf8mb4','user'=>(string)(getenv('SOKNA_TEST_DB_USER')?:'sokna'),'pass'=>(string)(getenv('SOKNA_TEST_DB_PASS')?:'sokna')]]);
$core->migrations()->migrate();$pdo=$core->database();
$pdo->prepare('INSERT INTO users(username,password_hash,display_name,role,active) VALUES(?,?,?,?,1)')->execute(['m8-admin',password_hash('x',PASSWORD_DEFAULT),'M8 Admin','admin']);$aid=(int)$pdo->lastInsertId();$admin=['id'=>$aid,'role'=>'admin','active'=>1];
@mkdir($dataRoot.'/secrets',0700,true);file_put_contents($dataRoot.'/secrets/runtime-health.token',str_repeat('h',64),LOCK_EX);
$agent=$core->printing()->createAgent('M8 Agent',$admin);m8a(strlen($agent['token'])===64,'agent token invalid');
$pdo->prepare("UPDATE print_destinations SET active=1,agent_id=?,windows_queue_name='Sokna Test' WHERE destination_key IN('prep_shared','customer_receipt')")->execute([(int)$agent['agent_id']]);
$auth=$core->printing()->authenticate('Bearer '.$agent['token']);m8a((int)$auth['id']===(int)$agent['agent_id'],'agent auth failed');
$rotatedToken=bin2hex(random_bytes(32));$rotation=$core->printing()->commitAgentTokenRotation((int)$agent['agent_id'],$rotatedToken,$aid);m8a((int)$rotation['agent_id']===(int)$agent['agent_id'],'rotation changed agent identity');
$oldRejected=false;try{$core->printing()->authenticate('Bearer '.$agent['token']);}catch(PrintException $e){$oldRejected=$e->errorCode==='unauthorized';}m8a($oldRejected,'old token remained valid after committed rotation');
$auth=$core->printing()->authenticate('Bearer '.$rotatedToken);m8a((int)$auth['id']===(int)$agent['agent_id'],'rotated token did not preserve agent identity');
$rotationTicket=$core->windowsServicesPairing()->createRotation($admin,(int)$agent['agent_id'],'M8 Agent Rotation');m8a(($rotationTicket['mode']??'')==='token_rotation','rotation ticket mode missing');
$exchange=$core->windowsServicesPairing()->exchange((string)$rotationTicket['pairing_code'],'127.0.0.1');$stagedToken=(string)($exchange['bundle']['print_agent_token']??'');m8a(strlen($stagedToken)===64,'rotation pairing bundle token invalid');
$stillOld=$core->printing()->authenticate('Bearer '.$rotatedToken);m8a((int)$stillOld['id']===(int)$agent['agent_id'],'rotation changed auth before confirm');
$core->windowsServicesPairing()->confirm((string)$rotationTicket['pairing_code'],'127.0.0.1');
$preConfirmRejected=false;try{$core->printing()->authenticate('Bearer '.$rotatedToken);}catch(PrintException $e){$preConfirmRejected=$e->errorCode==='unauthorized';}m8a($preConfirmRejected,'previous token remained valid after pairing confirm');
$auth=$core->printing()->authenticate('Bearer '.$stagedToken);m8a((int)$auth['id']===(int)$agent['agent_id'],'pairing rotation did not preserve agent identity');
$pdo->beginTransaction();$j=$core->printing()->enqueueTx('customer_receipt','customer_receipt',['hello'=>'world'],'test','1',$aid,'m8-job-1');$j2=$core->printing()->enqueueTx('customer_receipt','customer_receipt',['hello'=>'world'],'test','1',$aid,'m8-job-1');$pdo->commit();m8a(!$j['duplicate']&&$j2['duplicate']&&(int)$j['job_id']===(int)$j2['job_id'],'queue idempotency failed');
$c=['request_id'=>'m8-claim-0001','agent_version'=>'6.2.5','protocol_version'=>4,'limit'=>3,'ready_destination_keys'=>['customer_receipt']];$claim=$core->printing()->claim($auth,$c);m8a(count($claim['jobs'])===1,'claim did not reserve job');$claim2=$core->printing()->claim($auth,$c);m8a(!empty($claim2['idempotent'])&&$claim2['jobs'][0]['attempt_id']===$claim['jobs'][0]['attempt_id'],'claim replay drifted');
$job=$claim['jobs'][0];$accept=$core->printing()->accept($auth,['request_id'=>'m8-accept-0001','attempt_id'=>$job['attempt_id'],'lease_token'=>$job['lease_token'],'local_receipt_id'=>'receipt-m8-0001','content_sha256'=>$job['content_sha256']]);m8a($accept['status']==='claimed','accept fence failed');
$start=$core->printing()->start($auth,['request_id'=>'m8-start-00001','attempt_id'=>$job['attempt_id'],'lease_token'=>$job['lease_token']]);m8a($start['status']==='started','start failed');
$unknown=$core->printing()->report($auth,['request_id'=>'m8-report-0001','attempt_id'=>$job['attempt_id'],'lease_token'=>$job['lease_token'],'local_receipt_id'=>'receipt-m8-0001','status'=>'unknown','spooler_job_id'=>null,'retryable'=>false,'error_code'=>'spooler_unknown','error_message'=>'ambiguous']);m8a(!empty($unknown['requires_human_resolution']),'ambiguous print not fenced');
$state=(string)$pdo->query('SELECT status FROM print_jobs WHERE id='.(int)$j['job_id'])->fetchColumn();m8a($state==='unknown','unknown outcome not durable');
$core->printing()->resolveAmbiguous((int)$j['job_id'],'retry','operator verified no print',$admin);$state2=(string)$pdo->query('SELECT status FROM print_jobs WHERE id='.(int)$j['job_id'])->fetchColumn();m8a($state2==='pending','manual retry did not reopen queue');
$http=$core->printAgentV4Http()->handle('Bearer bad',['action'=>'probe','agent_version'=>'6.2.5']);m8a($http['status']===401,'Print API auth did not fail closed');
$source=file_get_contents(dirname(__DIR__).'/apps/local-web/src/Domain/Printing/PrintService.php');m8a(!preg_match('/Winspool|System\.Drawing|windows_queue.*PrintDocument/i',$source),'Local absorbed device/spooler implementation');
fwrite(STDOUT,"Local M8 Printing self-test: OK\n");
