<?php
declare(strict_types=1);
if(!in_array('mysql',PDO::getAvailableDrivers(),true)){fwrite(STDERR,"G3.3 qualification requires pdo_mysql.\n");exit(3);}if(!class_exists(ZipArchive::class)){fwrite(STDERR,"G3.3 qualification requires PHP zip.\n");exit(3);}if(!extension_loaded('sodium')){fwrite(STDERR,"G3.3 qualification requires sodium.\n");exit(3);}
require_once dirname(__DIR__).'/apps/public/bootstrap.php';
use Sokna\PublicEdge\Emergency\EmergencyAccessService;use Sokna\PublicEdge\Emergency\PairingSecretStore;use Sokna\PublicEdge\Emergency\PublicTakeoverService;use Sokna\PublicEdge\Emergency\PublicUpdateService;
function g33(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}function rmrf(string $p):void{if(!file_exists($p))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($p,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}rmdir($p);}function pkg33(string $zip,string $version,array $files):void{$z=new ZipArchive();$z->open($zip,ZipArchive::CREATE|ZipArchive::OVERWRITE);$rows=[];foreach($files as $p=>$c){$rows[]=['path'=>$p,'size'=>strlen($c),'sha256'=>hash('sha256',$c)];$z->addFromString('payload/'.$p,$c);}usort($rows,fn($a,$b)=>strcmp($a['path'],$b['path']));$m=['format'=>'sokna-component-package-v1','schema_version'=>1,'component'=>'public-edge','version'=>$version,'source_commit'=>str_repeat('b',40),'contracts'=>['local_public_contract'=>1],'files'=>$rows];$z->addFromString('manifest.json',json_encode($m,JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n");$z->close();}
$host=(string)(getenv('SOKNA_TEST_DB_HOST')?:'127.0.0.1');$port=(string)(getenv('SOKNA_TEST_DB_PORT')?:'3306');$base=(string)(getenv('SOKNA_TEST_DB_NAME')?:'sokna_m2');$user=(string)(getenv('SOKNA_TEST_DB_USER')?:'sokna');$pass=(string)(getenv('SOKNA_TEST_DB_PASS')?:'sokna');$rootUser=(string)(getenv('SOKNA_TEST_DB_ROOT_USER')?:'root');$rootPass=(string)(getenv('SOKNA_TEST_DB_ROOT_PASS')?:'root');$db=preg_replace('/[^A-Za-z0-9_]/','_',$base).'_public_g33';$root=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$rootUser,$rootPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$root->exec("DROP DATABASE IF EXISTS `{$db}`");$root->exec("CREATE DATABASE `{$db}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
$tmp=sys_get_temp_dir().'/sokna-g33-'.bin2hex(random_bytes(5));@mkdir($tmp.'/storage',0700,true);$old='machine-A';$new='machine-B';$oldSecret='old-'.bin2hex(random_bytes(32));$newSecret='new-'.bin2hex(random_bytes(32));$key=random_bytes(SODIUM_CRYPTO_SECRETBOX_KEYBYTES);$cfg=['db'=>['host'=>$host,'port'=>$port,'name'=>$db,'charset'=>'utf8mb4','user'=>$user,'pass'=>$pass],'app'=>['default_installation_id'=>$old,'storage_dir'=>$tmp.'/storage','cookie_secure'=>'0'],'relay'=>['installation_secrets'=>[$old=>$oldSecret],'clock_skew_seconds'=>300,'secret_encryption_key_base64'=>base64_encode($key)],'auth'=>[]];$core=sokna_public_bootstrap($cfg);$core->migrations()->migrate();$pdo=$core->database();$core->installationProjection()->sync($old,['display_name'=>'Cafe A','remote_enabled'=>true,'order_intake_enabled'=>true]);
$code='EMERGENCY-'.bin2hex(random_bytes(8));$access=$core->emergencyAccess();$access->provisionHash(password_hash($code,PASSWORD_DEFAULT),'test');g33($access->verify($code),'emergency access failed');$offer=$core->takeover()->createOffer($old,$new,1200,'test');g33(($offer['new_installation_id']??'')===$new,'takeover offer failed');$done=$core->takeover()->complete($new,(string)$offer['enrollment_code'],$newSecret,'Cafe B');g33(($done['old_revoked']??false)===true,'takeover completion failed');$a=$pdo->query("SELECT active,remote_enabled,order_intake_enabled,revoked_at FROM installations WHERE installation_id='machine-A'")->fetch(PDO::FETCH_ASSOC);g33((int)$a['active']===0&&(int)$a['remote_enabled']===0&&(int)$a['order_intake_enabled']===0&&!empty($a['revoked_at']),'old installation was not revoked');$b=$pdo->query("SELECT active,revoked_at FROM installations WHERE installation_id='machine-B'")->fetch(PDO::FETCH_ASSOC);g33((int)$b['active']===1&&empty($b['revoked_at']),'new installation not active');g33($core->pairingSecrets()->secret($new)===$newSecret,'encrypted pairing secret round-trip failed');
$verifier=$core->signedLocalRequests();$ts=(string)time();$body='{}';$sigOld=$verifier->sign($oldSecret,'POST','/api/v1/local/heartbeat',$ts,'nonce-old',$body);$vOld=$verifier->verify($old,'POST','/api/v1/local/heartbeat',$ts,'nonce-old',$body,$sigOld);g33(($vOld['error']??'')==='installation_revoked','revoked old secret remained accepted');$sigNew=$verifier->sign($newSecret,'POST','/api/v1/local/heartbeat',$ts,'nonce-new',$body);$vNew=$verifier->verify($new,'POST','/api/v1/local/heartbeat',$ts,'nonce-new',$body,$sigNew);g33(($vNew['ok']??false)===true,'new DB-stored pairing secret not accepted');
// Public updater on a disposable component tree. Stable Emergency files must survive every app release.
$component=$tmp.'/component';@mkdir($component.'/public',0700,true);@mkdir($component.'/src/Emergency',0700,true);@mkdir($component.'/resources',0700,true);file_put_contents($component.'/VERSION.txt','1.0.0');file_put_contents($component.'/bootstrap.php','<?php // old bootstrap');file_put_contents($component.'/public/index.php','<?php // old index');file_put_contents($component.'/public/emergency.php','<?php // STABLE EMERGENCY');file_put_contents($component.'/src/Emergency/stable.php','<?php // stable engine');file_put_contents($component.'/old-only.txt','old');file_put_contents($component.'/resources/update-trust-v1.json',json_encode(['signature_policy'=>'optional_until_release_qualification','ed25519_public_keys'=>[]]));$svc=new PublicUpdateService($component,$tmp.'/updater-storage',$component.'/resources/update-trust-v1.json',fn()=>true);$next=['VERSION.txt'=>'1.1.0','bootstrap.php'=>'<?php // new bootstrap','public/index.php'=>'<?php // new index','new-only.txt'=>'new'];pkg33($tmp.'/u.zip','1.1.0',$next);$st=$svc->stageUploadedZip($tmp.'/u.zip','test');g33($st['version']==='1.1.0','Public stage failed');$snap=$svc->activateStaged('test');g33($snap['active_version']==='1.1.0','Public activation failed');g33(str_contains((string)file_get_contents($component.'/public/emergency.php'),'STABLE EMERGENCY'),'stable emergency entrypoint was replaced');g33(is_file($component.'/new-only.txt')&&!is_file($component.'/old-only.txt'),'Public mutable payload swap failed');$back=$svc->rollback('test');g33($back['active_version']==='1.0.0'&&is_file($component.'/old-only.txt')&&!is_file($component.'/new-only.txt'),'Public rollback failed');g33(str_contains((string)file_get_contents($component.'/public/emergency.php'),'STABLE EMERGENCY'),'rollback changed stable emergency owner');
// A package attempting to replace Emergency must fail closed.
pkg33($tmp.'/bad.zip','2.0.0',['public/emergency.php'=>'hijack','bootstrap.php'=>'x','public/index.php'=>'y']);try{$svc->stageUploadedZip($tmp.'/bad.zip','test');g33(false,'stable-path package was accepted');}catch(\Sokna\PublicEdge\Emergency\PublicUpdateException $e){g33($e->errorCode==='stable_path_forbidden','wrong stable-path rejection code');}
$root->exec("DROP DATABASE IF EXISTS `{$db}`");rmrf($tmp);fwrite(STDOUT,"G3.3 Public Emergency/update/takeover MariaDB self-test: OK\n");
