<?php
declare(strict_types=1);
use Sokna\Local\Setup\BrowserSetupService;
$root=dirname(__DIR__,4);$local=dirname(__DIR__,2);
require_once $local.'/src/Setup/SetupException.php';require_once $local.'/src/Setup/BrowserSetupService.php';
$setup=new BrowserSetupService($root,$local);if($setup->status()['installed']){header('Location: /login.php');exit;}header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header("Content-Security-Policy: default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");header('Referrer-Policy: no-referrer');
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>راه‌اندازی سکنا</title><link rel="stylesheet" href="/scds.php?file=tokens.css"><link rel="stylesheet" href="/scds.php?file=components.css"><link rel="stylesheet" href="/assets/setup-wizard.css"></head><body><main class="sc-setup" data-setup-root>
<section class="sc-card sc-setup__hero"><div class="sc-card__body"><span class="sc-badge">Local Web Setup</span><h1>راه‌اندازی سکنا</h1><p>این مرحله فقط Local Web را آماده می‌کند. Apache، PHP و MariaDB پیش‌نیازهای مستقل محیط هستند.</p></div></section>
<div class="sc-alert" data-message hidden></div>
<section class="sc-card"><div class="sc-card__body"><h2>۱. پیش‌نیازها</h2><div data-preflight class="sc-setup__checks"></div><label class="sc-field"><span>مسیر داده</span><input class="sc-control" data-data-dir placeholder="C:\\SoknaData یا /srv/sokna-data" autocomplete="off"></label><button class="sc-button sc-button--secondary" data-action="preflight">بررسی دوباره</button></div></section>
<section class="sc-card"><div class="sc-card__body"><h2>۲. دیتابیس</h2><div class="sc-setup__grid"><label class="sc-field"><span>Host</span><input class="sc-control" data-db="host" value="127.0.0.1"></label><label class="sc-field"><span>Port</span><input class="sc-control" data-db="port" value="3306" inputmode="numeric"></label><label class="sc-field"><span>Database</span><input class="sc-control" data-db="name" value="sokna"></label><label class="sc-field"><span>User</span><input class="sc-control" data-db="user"></label><label class="sc-field sc-setup__span"><span>Password</span><input class="sc-control" data-db="pass" type="password" autocomplete="new-password"></label></div><label class="sc-check"><input type="checkbox" data-create-db> اگر دیتابیس وجود ندارد، ایجاد شود</label><button class="sc-button sc-button--secondary" data-action="test-db">تست اتصال</button><div data-db-result></div></div></section>
<section class="sc-card"><div class="sc-card__body"><h2>۳. مدیر و تنظیم اولیه</h2><div class="sc-setup__grid"><label class="sc-field"><span>نام کاربری مدیر</span><input class="sc-control" data-admin="user" autocomplete="username"></label><label class="sc-field"><span>رمز مدیر</span><input class="sc-control" data-admin="password" type="password" autocomplete="new-password"></label><label class="sc-field"><span>نام مجموعه</span><input class="sc-control" data-field="cafe_name" value="SOKNA"></label><label class="sc-field"><span>تعداد میز اولیه</span><input class="sc-control" data-field="table_count" value="10" type="number" min="1" max="100"></label><label class="sc-field sc-setup__span"><span>منطقه زمانی</span><input class="sc-control" data-field="timezone" value="Asia/Tehran"></label></div><button class="sc-button" data-action="install">راه‌اندازی Local Web</button><button class="sc-button sc-button--secondary" data-action="resume" hidden>ادامه Setup نیمه‌تمام</button></div></section>
<section class="sc-card"><div class="sc-card__body"><h2>۴. پایان</h2><p data-final>پس از migrations، ساخت مدیر، installation identity و health check، Setup قفل می‌شود.</p></div></section>
</main><script src="/assets/setup-wizard.js" defer></script><script src="/scds.php?file=scds.js" defer></script></body></html>
