<?php
declare(strict_types=1);
use Sokna\Local\Setup\BrowserSetupService;
use Sokna\Local\UI\LocalUrl;
$local=dirname(__DIR__,2);$root=dirname($local);
require_once $local.'/src/Core/Session.php';require_once $local.'/src/UI/LocalUrl.php';require_once $local.'/src/Setup/SetupException.php';require_once $local.'/src/Setup/BrowserSetupService.php';
$setup=new BrowserSetupService($root,$local);if($setup->status()['installed']){header('Location: '.LocalUrl::path('/login.php'));exit;}$version=trim((string)@file_get_contents($local.'/VERSION.txt'))?:'dev';$assetVersion=rawurlencode($version);header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('Pragma: no-cache');header('Expires: 0');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');$nonce=base64_encode(random_bytes(18));header("Content-Security-Policy: default-src 'self'; style-src 'self'; script-src 'self' 'nonce-{$nonce}'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");header('Referrer-Policy: no-referrer');
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><script nonce="<?=htmlspecialchars($nonce,ENT_QUOTES,'UTF-8')?>">(function(){try{var p=localStorage.getItem("sokna.theme")||"system";var d=p==="dark"||(p==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=d?"dark":"light"}catch(e){}})();</script><title>راه‌اندازی سکنا</title><meta name="theme-color" content="#0f6b66"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="application-name" content="سکنا"><link rel="manifest" href="<?=htmlspecialchars(LocalUrl::path('/manifest.webmanifest'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="icon" href="<?=htmlspecialchars(LocalUrl::path('/assets/favicon.ico'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>" sizes="any"><link rel="icon" type="image/png" sizes="16x16" href="<?=htmlspecialchars(LocalUrl::path('/assets/favicon-16.png'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="icon" type="image/png" sizes="32x32" href="<?=htmlspecialchars(LocalUrl::path('/assets/favicon-32.png'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="icon" type="image/png" sizes="48x48" href="<?=htmlspecialchars(LocalUrl::path('/assets/favicon-48.png'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="apple-touch-icon" sizes="180x180" href="<?=htmlspecialchars(LocalUrl::path('/assets/favicon-180.png'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="stylesheet" href="<?=htmlspecialchars(LocalUrl::path('/scds.php'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?file=tokens.css&amp;v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="stylesheet" href="<?=htmlspecialchars(LocalUrl::path('/scds.php'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?file=components.css&amp;v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="stylesheet" href="<?=htmlspecialchars(LocalUrl::path('/assets/setup-wizard.css'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"><link rel="stylesheet" href="<?=htmlspecialchars(LocalUrl::path('/assets/product-ui.css'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>"></head><body data-page="setup" data-app-base="<?=htmlspecialchars(LocalUrl::basePath(),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>">
<div class="sc-setup-shell"><button class="sc-icon-button sc-shell__theme sc-setup__theme" type="button" data-theme-toggle aria-label="فعال کردن حالت تیره" aria-pressed="false"><svg class="sc-theme-icon sc-theme-icon--moon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.2A8.5 8.5 0 0 1 8.8 4a8.6 8.6 0 1 0 11.2 11.2Z"/></svg><svg class="sc-theme-icon sc-theme-icon--sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"/></svg></button><main class="sc-setup" data-setup-root data-setup-version="<?=htmlspecialchars($version,ENT_QUOTES,'UTF-8')?>">
  <aside class="sc-setup__aside" aria-label="مراحل راه‌اندازی">
    <div class="sc-setup__brand"><span class="sc-setup__brand-mark" aria-hidden="true"><img src="<?=htmlspecialchars(LocalUrl::path('/assets/brand/Sokna-AppIcon-256.png'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>" alt="" width="256" height="256" decoding="async"></span><span class="sc-setup__brand-copy"><strong>سکنا</strong><span>راه‌اندازی محلی</span></span></div>
    <div><span class="sc-kicker">راه‌اندازی اولیه</span><h1>سامانه را در چند مرحله آماده کن.</h1><p>این مرحله فقط خود سامانه را آماده می‌کند؛ پیش‌نیازهای دستگاه از قبل آماده شده‌اند.</p></div>
    <div class="sc-setup__steps">
      <div class="sc-setup__step-nav"><b>۱</b><span>بررسی محیط</span></div>
      <div class="sc-setup__step-nav"><b>۲</b><span>اتصال دیتابیس</span></div>
      <div class="sc-setup__step-nav"><b>۳</b><span>حساب مدیر</span></div>
      <div class="sc-setup__step-nav"><b>۴</b><span>تکمیل نصب</span></div>
    </div>
  </aside>

  <div class="sc-setup__main">
    <header class="sc-setup__intro"><span class="sc-kicker">راه‌اندازی سامانه</span><h2>راه‌اندازی سکنا</h2><p>اطلاعات این فرم برای آماده‌سازی سامانه روی همین دستگاه و اتصال به اطلاعات کافه استفاده می‌شود.</p></header>
    <div class="sc-alert" data-message hidden></div>

    <section class="sc-card sc-setup__card" data-existing-install hidden><div class="sc-card__body">
      <div class="sc-setup__step-head"><span class="sc-setup__step-number" aria-hidden="true">!</span><div class="sc-setup__step-copy"><h2>نصب قبلی پیدا شد</h2><p>فایل‌های وب تازه هستند، اما وضعیت یک نصب کامل و معتبر از قبل روی دستگاه وجود دارد.</p></div></div>
      <div class="sc-alert sc-alert--warning">هیچ اطلاعاتی خودکار حذف یا جایگزین نمی‌شود. می‌توانی همان نصب قبلی را ادامه بدهی، یا وضعیت اتصال آن را آرشیو کنی و یک Setup تازه شروع کنی.</div>
      <div class="sc-setup__actions"><button class="sc-button" type="button" data-action="continue-existing">ادامه نصب موجود</button><button class="sc-button sc-button--danger" type="button" data-action="start-fresh">شروع نصب کاملاً جدید</button></div>
    </div></section>

    <section class="sc-card sc-setup__card" data-install-flow><div class="sc-card__body">
      <div class="sc-setup__step-head"><span class="sc-setup__step-number">۱</span><div class="sc-setup__step-copy"><h2>پیش‌نیازها و مسیر داده</h2><p>اول آماده‌بودن پیش‌نیازها و قابل‌نوشتن‌بودن محل داده را بررسی می‌کنیم.</p></div></div>
      <div data-preflight class="sc-setup__checks"></div>
      <label class="sc-field"><span class="sc-field__label">مسیر داده</span><input class="sc-control sc-canonical-id" data-data-dir dir="ltr" placeholder="D:\SOKNA\Data\LocalWeb" autocomplete="off"><small class="sc-help">برای نصب فعلی پیشنهاد می‌شود: <bdi dir="ltr">D:\SOKNA\Data\LocalWeb</bdi></small></label>
      <div class="sc-setup__actions"><button class="sc-button sc-button--secondary" type="button" data-action="preflight">بررسی دوباره</button></div>
    </div></section>

    <section class="sc-card sc-setup__card" data-install-flow><div class="sc-card__body">
      <div class="sc-setup__step-head"><span class="sc-setup__step-number">۲</span><div class="sc-setup__step-copy"><h2>اتصال دیتابیس</h2><p>اطلاعات دیتابیس را وارد کن و قبل از نصب اتصال را بررسی کن.</p></div></div>
      <div class="sc-setup__grid"><label class="sc-field"><span class="sc-field__label">میزبان</span><input class="sc-control" data-db="host" value="127.0.0.1" dir="ltr"></label><label class="sc-field"><span class="sc-field__label">درگاه</span><input class="sc-control" data-db="port" value="3306" inputmode="numeric" dir="ltr"></label><label class="sc-field"><span class="sc-field__label">نام دیتابیس</span><input class="sc-control" data-db="name" value="sokna" dir="ltr"></label><label class="sc-field"><span class="sc-field__label">کاربر دیتابیس</span><input class="sc-control" data-db="user" dir="ltr"></label><label class="sc-field sc-setup__span"><span class="sc-field__label">رمز دیتابیس</span><input class="sc-control" data-db="pass" type="password" dir="ltr" autocomplete="new-password"></label></div>
      <label class="sc-check"><input type="checkbox" data-create-db> اگر دیتابیس وجود ندارد، ایجاد شود</label>
      <div class="sc-setup__actions"><button class="sc-button sc-button--secondary" type="button" data-action="test-db">تست اتصال دیتابیس</button></div><div data-db-result></div>
    </div></section>

    <section class="sc-card sc-setup__card" data-install-flow><div class="sc-card__body">
      <div class="sc-setup__step-head"><span class="sc-setup__step-number">۳</span><div class="sc-setup__step-copy"><h2>مدیر و تنظیم اولیه</h2><p>حساب مدیر و چند تنظیم پایه مجموعه را مشخص کن.</p></div></div>
      <div class="sc-setup__grid"><label class="sc-field"><span class="sc-field__label">نام کاربری مدیر</span><input class="sc-control" data-admin="user" autocomplete="username" dir="auto"></label><label class="sc-field"><span class="sc-field__label">رمز مدیر</span><input class="sc-control" data-admin="password" type="password" autocomplete="new-password"></label><label class="sc-field"><span class="sc-field__label">نام مجموعه</span><input class="sc-control" data-field="cafe_name" value="SOKNA"></label><label class="sc-field"><span class="sc-field__label">تعداد میز اولیه</span><input class="sc-control" data-field="table_count" value="10" type="number" min="1" max="100"></label><label class="sc-field sc-setup__span"><span class="sc-field__label">منطقه زمانی</span><input class="sc-control" data-field="timezone" value="Asia/Tehran" dir="ltr"></label></div>
      <div class="sc-setup__actions"><button class="sc-button" type="button" data-action="install">راه‌اندازی سکنا</button><button class="sc-button sc-button--secondary" type="button" data-action="resume" hidden>ادامه راه‌اندازی نیمه‌تمام</button></div>
    </div></section>

    <section class="sc-card sc-setup__card" data-install-flow><div class="sc-card__body">
      <div class="sc-setup__step-head"><span class="sc-setup__step-number">۴</span><div class="sc-setup__step-copy"><h2>پایان و ورود</h2><p>پس از آماده‌شدن ساختار اطلاعات و حساب مدیر، راه‌اندازی نهایی می‌شود.</p></div></div><p data-final>بعد از تکمیل نصب، مستقیماً به صفحه ورود منتقل می‌شوی.</p>
    </div></section>
  </div>
</main>
<dialog class="sc-dialog" data-start-fresh-dialog aria-labelledby="sc-start-fresh-title"><form method="dialog" class="sc-card__body sc-form"><h2 id="sc-start-fresh-title">شروع راه‌اندازی تازه</h2><p>وضعیت اتصال نصب قبلی آرشیو می‌شود. دیتابیس و پوشه داده حذف نمی‌شوند.</p><div class="sc-alert sc-alert--warning">فقط وضعیت اتصال قبلی کنار گذاشته می‌شود تا Setup تازه شروع شود.</div><div class="sc-actions"><button class="sc-button sc-button--danger" type="submit" value="confirm">آرشیو و شروع تازه</button><button class="sc-button sc-button--secondary" type="button" data-start-fresh-cancel>انصراف</button></div></form></dialog>
</div>
<script src="<?=htmlspecialchars(LocalUrl::path('/assets/product-theme.js'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>" defer></script><script src="<?=htmlspecialchars(LocalUrl::path('/assets/setup-wizard.js'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>" defer></script><script src="<?=htmlspecialchars(LocalUrl::path('/scds.php'),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>?file=scds.js&amp;v=<?=htmlspecialchars($assetVersion,ENT_QUOTES,'UTF-8')?>" defer></script></body></html>
