<?php
declare(strict_types=1);

namespace Sokna\PublicEdge\Remote;

final class RemoteStaffPageRenderer
{
    public function __construct(private readonly string $basePath=''){}
    private const MODELS=[
        'operations'=>['cap'=>'operations.read','label'=>'عملیات'],
        'preparation'=>['cap'=>'preparation.read','label'=>'آماده‌سازی'],
        'inventory'=>['cap'=>'inventory.read','label'=>'انبار'],
        'inventory_cost'=>['cap'=>'inventory.cost.read','label'=>'بهای انبار'],
        'reports'=>['cap'=>'reports.read','label'=>'گزارش'],
        'notifications'=>['cap'=>'notifications.read','label'=>'اعلان‌ها'],
        'deferred_context'=>['cap'=>'deferred.context','label'=>'کار آفلاین'],
    ];
    public function login(string $installationId,string $error=''): array
    {
        $e=$error!==''?'<div class="rs-alert is-error" role="alert">'.$this->e($error).'</div>':'';
        $html='<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#0f6b66"><link rel="manifest" href="'.$this->e($this->u('/staff.webmanifest')).'"><link rel="apple-touch-icon" sizes="180x180" href="'.$this->e($this->u('/assets/favicon-180.png')).'"><title>ورود همکار | سکنا</title><link rel="stylesheet" href="'.$this->e($this->u('/assets/scds/remote-staff.css')).'"><script src="'.$this->e($this->u('/assets/scds/staff-pwa.js')).'" defer></script></head><body class="rs-body rs-body--auth" data-base-path="'.$this->e($this->base()).'"><main class="rs-login"><section class="rs-auth-shell"><aside class="rs-auth-brand" aria-label="سکنا"><div class="rs-brand"><span class="rs-brand-mark" aria-hidden="true">س</span><span class="rs-brand-copy"><strong>سکنا</strong><small>دسترسی راه‌دور همکاران</small></span></div><div class="rs-auth-copy"><span class="rs-eyebrow">پنل همکار</span><h1>دسترسی امن به کارهای روزمره</h1><p>فقط قابلیت‌هایی که مدیر در سامانه محلی برای این حساب فعال کرده، اینجا در دسترس است.</p></div></aside><section class="rs-card rs-auth-card"><div class="rs-section-head"><span class="rs-eyebrow">ورود</span><h2>ورود همکار</h2><p>با رمز دسترسی راه‌دور خود وارد شوید.</p></div>'.$e.'<form method="post" action="'.$this->e($this->u('/staff/login')).'" class="rs-stack"><input type="hidden" name="installation_id" value="'.$this->e($installationId).'"><label>نام کاربری<input name="username" autocomplete="username" required></label><label>رمز دسترسی راه‌دور<input name="password" type="password" autocomplete="current-password" required></label><button class="rs-button rs-button--primary" type="submit">ورود</button></form><div class="rs-device-tools rs-device-tools--auth"><button class="rs-button rs-button--secondary" type="button" data-pwa-install>نصب برنامه</button><span class="rs-device-status" data-device-status>برای دسترسی سریع‌تر می‌توانید برنامه را نصب کنید.</span></div></section></section></main></body></html>';
        return ['status'=>200,'headers'=>['Content-Type'=>'text/html; charset=utf-8','Cache-Control'=>'no-store'],'body'=>$html];
    }
    public function dashboard(array $session): array
    {
        $caps=array_map('strval',(array)($session['capabilities']??[]));$all=in_array('*',$caps,true);$buttons='';
        foreach(self::MODELS as $key=>$meta){if(!$all&&!in_array($meta['cap'],$caps,true)&&!($key==='preparation'&&in_array('preparation.monitor',$caps,true)))continue;$buttons.='<button type="button" data-model="'.$this->e($key).'">'.$this->e($meta['label']).'</button>';}
        $name=trim((string)($session['display_name']??''));$actions='';
        if($all||in_array('orders.mutate',$caps,true))$actions.='<section class="rs-action rs-order-review" data-order-review><h2>سفارش‌های منتظر</h2><p>در حال دریافت سفارش‌ها…</p></section>';
        if($all||in_array('preparation.mutate',$caps,true))$actions.='<section class="rs-action rs-preparation-claim" data-preparation-claim><h2>آماده‌سازی</h2><p>در حال دریافت کارهای آماده‌سازی…</p></section>';
        if($all||in_array('orders.table_draft',$caps,true))$actions.='<section class="rs-action rs-table-draft" data-table-draft><h2>پیش‌نویس میز</h2><label>میز<select data-draft-table><option value="">در حال دریافت…</option></select></label><div class="rs-draft-meta" data-draft-meta>ابتدا میز را انتخاب کنید.</div><div class="rs-draft-add"><label>آیتم<select data-draft-item><option value="">انتخاب آیتم</option></select></label><label>تعداد<input data-draft-qty type="number" min="1" max="50" value="1" inputmode="numeric"></label><button type="button" data-draft-add>افزودن</button></div><div class="rs-draft-lines" data-draft-lines><p>آیتمی در پیش‌نویس نیست.</p></div><label>یادداشت<textarea data-draft-note maxlength="500" rows="2"></textarea></label><button type="button" data-draft-save disabled>ذخیره پیش‌نویس</button><div class="rs-draft-final-actions"><button type="button" data-draft-finalize disabled>ثبت سفارش</button><button type="button" class="rs-danger-button" data-draft-cancel disabled>لغو پیش‌نویس</button></div><div class="rs-action-state" data-draft-state></div></section>';
        if($all||in_array('finance.settle',$caps,true))$actions.='<form class="rs-action" data-action="settlement"><h2>تسویه راه‌دور</h2><label>حساب<select name="session_id" data-settlement-sessions required></select></label><button type="submit">ثبت تسویه کامل</button><div class="rs-action-state" data-action-state></div></form>';
        if($all||in_array('supply.need.defer',$caps,true))$actions.='<form class="rs-action" data-action="supply"><h2>نیاز خرید</h2><label>قلم<select name="inventory_item_id" data-inventory-items required></select></label><label>مقدار<input name="quantity_major" inputmode="decimal" required></label><label>بخش<select name="department"><option value="shared">مشترک</option><option value="kitchen">آشپزخانه</option><option value="bar">بار</option></select></label><label>یادداشت<input name="note"></label><button type="submit">ثبت برای همگام‌سازی</button><div class="rs-action-state" data-action-state></div></form>';
        if($all||in_array('subscriber.payment.defer',$caps,true))$actions.='<form class="rs-action" data-action="subscriber"><h2>پرداخت مشترک</h2><label>مشترک<select name="subscriber_id" data-subscribers required></select></label><label>مبلغ<input name="amount" inputmode="numeric" required></label><label>مرجع<input name="reference"></label><button type="submit">ثبت پرداخت</button><div class="rs-action-state" data-action-state></div></form>';
        $showDeferred=$all||in_array('supply.need.defer',$caps,true)||in_array('subscriber.payment.defer',$caps,true);$deferred=$showDeferred?'<div class="rs-deferred-list" data-deferred-list></div>':'';$actions=$actions!==''?'<section class="rs-card rs-actions-panel"><h1>عملیات راه‌دور</h1><div class="rs-action-grid">'.$actions.'</div>'.$deferred.'</section>':'';
        $html='<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#0f6b66"><link rel="manifest" href="'.$this->e($this->u('/staff.webmanifest')).'"><link rel="apple-touch-icon" sizes="180x180" href="'.$this->e($this->u('/assets/favicon-180.png')).'"><title>دسترسی راه‌دور | سکنا</title><link rel="stylesheet" href="'.$this->e($this->u('/assets/scds/remote-staff.css')).'"><script src="'.$this->e($this->u('/assets/scds/remote-staff.js')).'" defer></script><script src="'.$this->e($this->u('/assets/scds/staff-pwa.js')).'" defer></script></head><body class="rs-body rs-body--dashboard" data-base-path="'.$this->e($this->base()).'"><a class="rs-skip-link" href="#rsMain">پرش به محتوای اصلی</a><header class="rs-header"><div class="rs-header__inner"><div class="rs-brand"><span class="rs-brand-mark" aria-hidden="true">س</span><span class="rs-brand-copy"><strong>سکنا</strong><small>دسترسی راه‌دور</small></span></div><div class="rs-header__account"><div class="rs-user-card"><strong>'.$this->e($name!==''?$name:'همکار سکنا').'</strong><small>همکار سکنا</small></div><form method="post" action="'.$this->e($this->u('/staff/logout')).'"><button class="rs-button rs-button--header" type="submit">خروج</button></form></div></div></header><main class="rs-main" id="rsMain"><section class="rs-page-head"><div class="rs-page-head__copy"><span class="rs-eyebrow">پنل همکار</span><h1>دسترسی راه‌دور</h1><p>وضعیت و عملیات مجاز این حساب از سامانه محلی سکنا همگام می‌شود.</p></div><div class="rs-alert rs-connectivity" data-connectivity>در حال دریافت آخرین projection…</div></section><section class="rs-device-tools" aria-label="برنامه و اعلان دستگاه"><div><strong>این دستگاه</strong><span class="rs-device-status" data-device-status>در حال بررسی وضعیت نصب و اعلان…</span></div><div class="rs-device-actions"><button class="rs-button rs-button--secondary" type="button" data-pwa-install>نصب برنامه</button><button class="rs-button rs-button--secondary" type="button" data-push-toggle>فعال‌کردن اعلان</button><button class="rs-button rs-button--secondary" type="button" data-push-test hidden>تست اعلان</button></div></section><nav class="rs-tabs" aria-label="بخش‌ها">'.$buttons.'</nav>'.$actions.'<section class="rs-card rs-read-panel"><div class="rs-card-head"><div><span class="rs-eyebrow">اطلاعات همگام‌شده</span><h2 data-title>وضعیت</h2></div><div data-state class="rs-state"></div></div><div data-output class="rs-output" aria-live="polite"><div class="rs-model-empty"><strong>یک بخش را انتخاب کنید.</strong><span>اطلاعات همان بخش اینجا نمایش داده می‌شود.</span></div></div></section></main></body></html>';
        return ['status'=>200,'headers'=>['Content-Type'=>'text/html; charset=utf-8','Cache-Control'=>'no-store'],'body'=>$html];
    }
    private function base(): string{$b='/' . trim(str_replace('\\','/',$this->basePath),'/');return $b==='/'?'':rtrim($b,'/');}
    private function u(string $path): string{return $this->base().'/'.ltrim($path,'/');}
    private function e(string $v): string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
