<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';
$user=LocalPage::requireAny($core,['inventory_operations','inventory_finalize','inventory_manage','preparation','shift_supervision']);
$isAdmin=(string)($user['role']??'')==='admin';$canOps=$isAdmin||$core->auth()->hasCapability('inventory_operations',$user);$canManage=$isAdmin||$core->auth()->hasCapability('inventory_manage',$user);$canFinalize=$isAdmin||$core->auth()->hasCapability('inventory_finalize',$user);$canBuy=$isAdmin||$canOps||$canManage||$canFinalize;$csrf=WebAction::csrfToken();
ProductShell::start($core,$user,'انبار، تأمین و هزینه‌ها','operations','موجودی، نیازهای خرید و هزینه‌های کافه را از یک فضای کاری مدیریت کن.',true);
?>
<section class="sc-workspace" data-operations-workspace data-api="operations/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>" data-admin="<?= $isAdmin?'1':'0' ?>" data-can-ops="<?= $canOps?'1':'0' ?>" data-can-manage="<?= $canManage?'1':'0' ?>" data-can-finalize="<?= $canFinalize?'1':'0' ?>" data-can-buy="<?= $canBuy?'1':'0' ?>">
  <div class="sc-toolbar sc-local-nav"><div class="sc-tabs" role="tablist" aria-label="عملیات"><button class="sc-tab" role="tab" aria-selected="true" type="button" data-tab="inventory">انبار</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="supply">تأمین و خرید</button><?php if($isAdmin): ?><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="expenses">هزینه‌ها</button><button class="sc-tab" role="tab" aria-selected="false" type="button" data-tab="deferred">موارد نیازمند بررسی</button><?php endif; ?></div><button class="sc-button sc-button--secondary" type="button" data-refresh>تازه‌سازی</button></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال دریافت وضعیت عملیات…</div>

  <section class="sc-work-panel" data-panel="inventory">
    <div class="sc-section-head"><div><h2>موجودی</h2><p>ثبت کالا، اصلاح دستی و شمارش از سرویس انبار عبور می‌کند.</p></div><div class="sc-actions"><?php if($canOps): ?><button class="sc-button sc-button--secondary" type="button" data-open="count-start">شروع شمارش</button><?php endif; ?><?php if($canManage): ?><button class="sc-button" type="button" data-open="item-create">کالای جدید</button><?php endif; ?></div></div>
    <div class="sc-summary-grid"><article class="sc-card sc-metric"><span>کالای فعال</span><strong data-metric="inventory-items">—</strong><small>کالاهای قابل استفاده</small></article><article class="sc-card sc-metric"><span>نیاز به بررسی</span><strong data-metric="inventory-review">—</strong><small>اقلام ایجادشده یا نیازمند بازبینی</small></article><article class="sc-card sc-metric"><span>شمارش باز</span><strong data-metric="count-open">—</strong><small>فقط یک شمارش هم‌زمان</small></article></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>کالا</th><th>دسته</th><th>موجودی</th><th>وضعیت</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-inventory-list></tbody></table></div>
    <section class="sc-card sc-hidden" data-count-panel><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h3 data-count-title>شمارش باز</h3><p>مقدار واقعی هر قلم را ثبت کن؛ نهایی‌سازی نیاز به دسترسی جدا دارد.</p></div><div class="sc-actions"><button class="sc-button sc-button--danger" type="button" data-count-cancel>لغو شمارش</button><button class="sc-button" type="button" data-count-finalize>نهایی‌سازی</button></div></div><div class="sc-stack" data-count-lines></div></div></section>
    <section class="sc-card sc-ledger-card"><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h3>حرکت‌های اخیر</h3><p>آخرین ورود، خروج و اصلاح موجودی را بدون تکرار خلاصه‌های بالا ببین.</p></div></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>زمان</th><th>کالا</th><th>نوع</th><th>مقدار</th><th>بخش</th></tr></thead><tbody data-movement-list></tbody></table></div></div></section>
  </section>

  <section class="sc-work-panel" data-panel="supply" hidden>
    <div class="sc-section-head"><div><h2>تأمین و خرید</h2><p>نیازها ابتدا ثبت می‌شوند و سپس وارد وضعیت «در حال خرید» و «تحویل» می‌شوند.</p></div><button class="sc-button" type="button" data-open="need-create">ثبت نیاز</button></div>
    <div class="sc-card-grid" data-supply-groups></div>
    <section class="sc-card sc-ledger-card"><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h3>تحویل‌های اخیر</h3><p>رسید خریدهای تحویل‌شده؛ جزئیات نیازهای باز در کارت‌های بالاتر باقی می‌ماند.</p></div></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>زمان</th><th>کالا</th><th>مقدار</th><th>هزینه</th><th>تأمین‌کننده</th></tr></thead><tbody data-receipt-list></tbody></table></div></div></section>
  </section>

  <?php if($isAdmin): ?><section class="sc-work-panel sc-data-panel" data-panel="deferred" hidden>
    <div class="sc-section-head"><div><h2>موارد نیازمند بررسی</h2><p>مواردی که به‌دلیل تغییر هم‌زمان اطلاعات نیاز به تصمیم مدیر دارند، این‌جا تعیین تکلیف می‌شوند.</p></div></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>زمان</th><th>نوع</th><th>کاربر</th><th>توضیح</th><th>عملیات</th></tr></thead><tbody data-deferred-reviews></tbody></table></div>
  </section><?php endif; ?>

  <?php if($isAdmin): ?><section class="sc-work-panel sc-data-panel" data-panel="expenses" hidden>
    <div class="sc-section-head"><div><h2>هزینه‌های کافه</h2><p>سند هزینه حذف نمی‌شود؛ اصلاح تاریخچه با برگشت/سند جبرانی انجام می‌شود.</p></div><button class="sc-button" type="button" data-open="expense-create">ثبت هزینه</button></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>زمان</th><th>دسته</th><th>شرح</th><th>مبلغ</th><th>دوره</th><th>وضعیت</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-expense-list></tbody></table></div>
  </section><?php endif; ?>

  <dialog class="sc-dialog" data-dialog="item-create" aria-labelledby="sc-dialog-title-operations-item-create"><form method="dialog" class="sc-card__body sc-form" data-form="item-create"><h2 id="sc-dialog-title-operations-item-create">کالای انبار جدید</h2><label class="sc-field"><span class="sc-field__label">نام</span><input class="sc-control" name="name" required></label><label class="sc-field"><span class="sc-field__label">دسته</span><select class="sc-control" name="category" data-category-select></select></label><label class="sc-field"><span class="sc-field__label">واحد پایه</span><select class="sc-control" name="base_unit"><option value="count">عدد</option><option value="g">گرم</option><option value="ml">میلی‌لیتر</option></select></label><label class="sc-field"><span class="sc-field__label">بخش پیش‌فرض</span><select class="sc-control" name="default_department"><option value="shared">مشترک</option><option value="bar">بار</option><option value="kitchen">آشپزخانه</option></select></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ثبت کالا</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="inventory-adjust" aria-labelledby="sc-dialog-title-operations-inventory-adjust"><form method="dialog" class="sc-card__body sc-form" data-form="inventory-adjust"><h2 id="sc-dialog-title-operations-inventory-adjust">اصلاح دستی موجودی</h2><input type="hidden" name="item_id"><p class="sc-muted" data-adjust-item></p><label class="sc-field"><span class="sc-field__label">نوع</span><select class="sc-control" name="kind"><option value="waste">ضایعات / خروج</option><option value="count_adjustment">اصلاح مقدار</option></select></label><label class="sc-field"><span class="sc-field__label">جهت اصلاح</span><select class="sc-control" name="direction"><option value="remove">کاهش</option><option value="add">افزایش</option></select></label><label class="sc-field"><span class="sc-field__label">مقدار در واحد اصلی</span><input class="sc-control" name="quantity_major" inputmode="decimal" required></label><label class="sc-field"><span class="sc-field__label">بخش</span><select class="sc-control" name="department"><option value="shared">مشترک</option><option value="bar">بار</option><option value="kitchen">آشپزخانه</option></select></label><label class="sc-field"><span class="sc-field__label">یادداشت</span><textarea class="sc-control" name="note" rows="3"></textarea></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ثبت حرکت</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="count-start" aria-labelledby="sc-dialog-title-operations-count-start"><form method="dialog" class="sc-card__body sc-form" data-form="count-start"><h2 id="sc-dialog-title-operations-count-start">شروع شمارش</h2><label class="sc-field"><span class="sc-field__label">عنوان</span><input class="sc-control" name="title" value="شمارش دوره‌ای"></label><label class="sc-field"><span class="sc-field__label">نوع</span><select class="sc-control" name="session_type"><option value="periodic">دوره‌ای</option><option value="opening">موجودی اولیه</option></select></label><label class="sc-field"><span class="sc-field__label">محدوده</span><select class="sc-control" name="scope_type"><option value="full">همه کالاها</option><option value="category">یک دسته</option></select></label><label class="sc-field"><span class="sc-field__label">دسته در شمارش دسته‌ای</span><select class="sc-control" name="scope_category_key" data-category-select></select></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">شروع</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="need-create" aria-labelledby="sc-dialog-title-operations-need-create"><form method="dialog" class="sc-card__body sc-form" data-form="need-create"><h2 id="sc-dialog-title-operations-need-create">ثبت نیاز تأمین</h2><label class="sc-field"><span class="sc-field__label">کالای انبار</span><select class="sc-control" name="inventory_item_id" data-item-select><option value="0">خارج از فهرست</option></select></label><label class="sc-field"><span class="sc-field__label">نام خارج از فهرست</span><input class="sc-control" name="free_name"></label><label class="sc-field"><span class="sc-field__label">واحد برای مورد خارج از فهرست</span><select class="sc-control" name="base_unit"><option value="count">عدد</option><option value="g">گرم</option><option value="ml">میلی‌لیتر</option></select></label><label class="sc-field"><span class="sc-field__label">مقدار موردنیاز</span><input class="sc-control" name="quantity_major" inputmode="decimal" required></label><label class="sc-field"><span class="sc-field__label">بخش</span><select class="sc-control" name="department"><option value="shared">مشترک</option><option value="bar">بار</option><option value="kitchen">آشپزخانه</option></select></label><label class="sc-field"><span class="sc-field__label">یادداشت</span><textarea class="sc-control" name="note" rows="3"></textarea></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ثبت نیاز</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="supply-receive" aria-labelledby="sc-dialog-title-operations-supply-receive"><form method="dialog" class="sc-card__body sc-form" data-form="supply-receive"><h2 id="sc-dialog-title-operations-supply-receive">ثبت تحویل خرید</h2><input type="hidden" name="group_key"><input type="hidden" name="expected_preparing_quantity_base"><p class="sc-muted" data-receive-item></p><label class="sc-field"><span class="sc-field__label">مقدار تحویل‌شده</span><input class="sc-control" name="unit_count" inputmode="decimal" required></label><label class="sc-field"><span class="sc-field__label">هزینه کل</span><input class="sc-control" name="total_cost" inputmode="numeric"></label><label class="sc-field"><span class="sc-field__label">تأمین‌کننده</span><input class="sc-control" name="supplier"></label><label class="sc-field"><span class="sc-field__label">یادداشت</span><textarea class="sc-control" name="note" rows="3"></textarea></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ثبت تحویل</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <?php if($isAdmin): ?><dialog class="sc-dialog" data-dialog="expense-create" aria-labelledby="sc-dialog-title-operations-expense-create"><form method="dialog" class="sc-card__body sc-form" data-form="expense-create"><h2 id="sc-dialog-title-operations-expense-create">ثبت هزینه</h2><label class="sc-field"><span class="sc-field__label">دسته</span><select class="sc-control" name="category_key" data-expense-category></select></label><label class="sc-field"><span class="sc-field__label">مبلغ</span><input class="sc-control" name="amount" inputmode="numeric" required></label><label class="sc-field"><span class="sc-field__label">شرح</span><textarea class="sc-control" name="description" rows="3"></textarea></label><label class="sc-field"><span class="sc-field__label">زمان وقوع</span><input class="sc-control" type="datetime-local" name="occurred_at" required></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ثبت هزینه</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>
  <dialog class="sc-dialog" data-dialog="expense-reverse" aria-labelledby="sc-dialog-title-operations-expense-reverse"><form method="dialog" class="sc-card__body sc-form" data-form="expense-reverse"><h2 id="sc-dialog-title-operations-expense-reverse">برگشت هزینه</h2><input type="hidden" name="expense_id"><p class="sc-muted" data-reverse-expense></p><label class="sc-field"><span class="sc-field__label">دلیل</span><textarea class="sc-control" name="reason" rows="3" required></textarea></label><div class="sc-actions"><button class="sc-button sc-button--danger" type="submit" value="submit">ثبت برگشت</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog><?php endif; ?>
</section>
<script src="<?=ProductShell::asset('assets/operations-workspace.js')?>" defer></script>
<?php if($isAdmin): ?><script src="<?=ProductShell::asset('assets/deferred-review-workspace.js')?>" defer></script><?php endif; ?>
<?php ProductShell::end(); ?>
