<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAdmin($core);$csrf=WebAction::csrfToken();
ProductShell::start($core,$user,'مرکز سیستم','system','سلامت، تشخیص، Update و Recovery در یک control plane؛ lifecycle owner هر component حفظ می‌شود.');
?>
<section class="sc-workspace" data-system-workspace data-api="/system/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>">
  <div class="sc-toolbar"><div class="sc-actions"><button class="sc-button sc-button--secondary" type="button" data-refresh>تازه‌سازی</button><button class="sc-button sc-button--secondary" type="button" data-public-sync>Sync Public</button><button class="sc-button" type="button" data-support>ساخت بسته پشتیبانی</button></div></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال بررسی وضعیت سیستم…</div>
  <div class="sc-tabs" role="tablist"><button class="sc-tab" type="button" role="tab" aria-selected="true" data-tab="health">سلامت و تشخیص</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="updates">Update Center</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="recovery">Backup / Recovery</button></div>
  <div data-panel="health">
    <section class="sc-card"><div class="sc-card__body"><div class="sc-section-head"><div><h2>خلاصه سلامت</h2><p>موارد بحرانی مانع اتکای عملیاتی هستند؛ هشدارها نیاز به بررسی دارند.</p></div><span class="sc-badge" data-overall>—</span></div><div class="sc-card-grid" data-checks></div></div></section>
    <section class="sc-card-grid" data-components></section>
    <section class="sc-card"><div class="sc-card__body"><div class="sc-section-head"><div><h2>رخدادهای اخیر</h2><p>فقط log ساخت‌یافته Local و با redaction نمایش داده می‌شود.</p></div></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>زمان</th><th>سطح</th><th>رخداد</th><th>Correlation</th></tr></thead><tbody data-logs></tbody></table></div></div></section>
  </div>
  <div data-panel="updates" hidden>
    <section class="sc-card"><div class="sc-card__body"><div class="sc-section-head"><div><h2>اجزای ثبت‌شده</h2><p>Local فقط lifecycle خودش را اجرا می‌کند؛ Runtime/Print و Public ownerهای مستقل دارند.</p></div></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>جزء</th><th>نسخه</th><th>سازگاری</th><th>سلامت</th><th>Update owner</th><th>عمل</th></tr></thead><tbody data-update-components></tbody></table></div></div></section>
    <section class="sc-card"><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h2>Local Web</h2><p>بسته immutable ZIP را verify و stage کن؛ سپس Update یا same-version Repair را اجرا کن.</p></div><span class="sc-badge" data-local-version>—</span></div><form data-update-upload class="sc-stack" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>"><label>بسته Update<input class="sc-control" type="file" name="package" accept=".zip,application/zip" required></label><button class="sc-button" type="submit">Verify + Stage</button></form><div class="sc-list-item" data-staged>بسته stage‌شده‌ای وجود ندارد.</div><div class="sc-actions"><button class="sc-button" type="button" data-activate>فعال‌سازی Update</button><button class="sc-button sc-button--secondary" type="button" data-repair>Repair همان نسخه</button><button class="sc-button sc-button--danger" type="button" data-rollback>Rollback به LKG</button></div><div class="sc-alert sc-alert--info">Signature contract در engine پیاده شده است؛ تا G6 release qualification سیاست pre-release اجازه بسته بدون signature می‌دهد. بسته دارای signature نامعتبر همیشه رد می‌شود.</div></div></section>
    <section class="sc-card"><div class="sc-card__body"><div class="sc-section-head"><div><h2>Recovery مستقل از bootstrap</h2><p>یک کد recovery بساز و خارج از برنامه نگهدار. مسیر اضطراری <code>/local-recovery.php</code> بدون bootstrap اصلی آخرین LKG را برمی‌گرداند.</p></div></div><div class="sc-actions"><button class="sc-button sc-button--secondary" type="button" data-recovery-code>ساخت/چرخش کد Recovery</button><a class="sc-button sc-button--secondary" href="/local-recovery.php">بازکردن Recovery</a></div><div class="sc-alert sc-alert--warning sc-hidden" data-recovery-secret></div></div></section>
  </div>
  <div data-panel="recovery" hidden>
    <section class="sc-card"><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h2>Business Backup</h2><p>داده کسب‌وکار رمزنگاری می‌شود؛ identityهای ماشین داخل backup نیستند.</p></div></div><label>رمز Backup<input class="sc-control" type="password" minlength="12" data-backup-pass autocomplete="new-password"></label><div class="sc-actions"><button class="sc-button" type="button" data-backup-create>ساخت Backup رمزنگاری‌شده</button></div><div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>فایل</th><th>حجم</th><th>SHA256</th><th>عمل</th></tr></thead><tbody data-backups></tbody></table></div></div></section>
    <section class="sc-card"><div class="sc-card__body sc-stack"><div class="sc-section-head"><div><h2>بازیابی Backup</h2><p>Restore فقط روی نصب/DB خالی پذیرفته می‌شود. بعد از restore، machine identity باید دوباره provision شود.</p></div></div><form data-recovery-upload class="sc-stack" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>"><label>فایل SKBF<input class="sc-control" type="file" name="backup" required></label><button class="sc-button sc-button--secondary" type="submit">آپلود Backup</button></form><label>شناسه Backup برای Inspect/Restore<input class="sc-control" data-restore-id placeholder="uploaded-..."></label><label>رمز Backup<input class="sc-control" type="password" data-restore-pass autocomplete="off"></label><div class="sc-actions"><button class="sc-button sc-button--secondary" type="button" data-backup-inspect>بررسی Backup</button><button class="sc-button sc-button--danger" type="button" data-backup-restore>Restore روی مقصد خالی</button></div><pre class="sc-code sc-hidden" data-backup-manifest></pre><div class="sc-alert sc-alert--info"><strong>Machine takeover:</strong> Local فقط نیاز به re-enrollment را نشان می‌دهد؛ سوییچ Public A→B و Emergency path در G3 تکمیل می‌شود.</div></div></section>
  </div>
</section>
<script src="/assets/system-diagnostics.js" defer></script>
<?php ProductShell::end(); ?>
