<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAdmin($core);$csrf=WebAction::csrfToken();
ProductShell::start($core,$user,'کمپین و رویداد','marketing','کمپین‌ها و رویدادها در Local مالکیت دارند؛ فقط موارد عمومیِ فعال به منوی مهمان publish می‌شوند.');
?>
<section class="sc-workspace" data-marketing data-api="/marketing/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>">
<div class="sc-alert" data-status role="status">در حال دریافت…</div>
<div class="sc-card-grid">
<section class="sc-card"><form class="sc-card__body sc-form" data-campaign-form><h2>کمپین</h2><input type="hidden" name="id" value="0"><label class="sc-field"><span class="sc-field__label">نام داخلی</span><input class="sc-control" name="name" required maxlength="160"></label><label class="sc-field"><span class="sc-field__label">عنوان مهمان</span><input class="sc-control" name="headline" required maxlength="200"></label><label class="sc-field"><span class="sc-field__label">متن</span><textarea class="sc-control" name="body" rows="3"></textarea></label><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">وضعیت</span><select class="sc-control" name="status"><option value="draft">پیش‌نویس</option><option value="scheduled">زمان‌بندی</option><option value="active">فعال</option><option value="paused">متوقف</option><option value="completed">تمام‌شده</option><option value="archived">آرشیو</option></select></label><label class="sc-field"><span class="sc-field__label">شروع</span><input class="sc-control" type="datetime-local" name="starts_at"></label><label class="sc-field"><span class="sc-field__label">پایان</span><input class="sc-control" type="datetime-local" name="ends_at"></label></div><label><input type="checkbox" name="public_visible"> نمایش در منوی عمومی</label><button class="sc-button" type="submit">ذخیره کمپین</button></form></section>
<section class="sc-card"><form class="sc-card__body sc-form" data-event-form><h2>رویداد</h2><input type="hidden" name="id" value="0"><label class="sc-field"><span class="sc-field__label">عنوان</span><input class="sc-control" name="title" required maxlength="180"></label><label class="sc-field"><span class="sc-field__label">توضیح</span><textarea class="sc-control" name="description" rows="3"></textarea></label><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">وضعیت</span><select class="sc-control" name="status"><option value="draft">پیش‌نویس</option><option value="scheduled">زمان‌بندی</option><option value="active">فعال</option><option value="completed">تمام‌شده</option><option value="cancelled">لغوشده</option><option value="archived">آرشیو</option></select></label><label class="sc-field"><span class="sc-field__label">شروع</span><input class="sc-control" type="datetime-local" name="starts_at" required></label><label class="sc-field"><span class="sc-field__label">پایان</span><input class="sc-control" type="datetime-local" name="ends_at"></label><label class="sc-field"><span class="sc-field__label">ظرفیت</span><input class="sc-control" type="number" min="1" name="capacity"></label><label class="sc-field"><span class="sc-field__label">محل</span><input class="sc-control" name="location_label" maxlength="180"></label></div><label><input type="checkbox" name="public_visible"> نمایش در منوی عمومی</label><button class="sc-button" type="submit">ذخیره رویداد</button></form></section>
</div>
<div class="sc-card-grid"><section class="sc-card"><div class="sc-card__body"><h2>کمپین‌ها</h2><div class="sc-table-wrap"><table class="sc-table"><thead><tr><th>نام</th><th>عنوان</th><th>وضعیت</th><th>عمومی</th><th></th></tr></thead><tbody data-campaign-list></tbody></table></div></div></section><section class="sc-card"><div class="sc-card__body"><h2>رویدادها</h2><div class="sc-table-wrap"><table class="sc-table"><thead><tr><th>عنوان</th><th>شروع</th><th>وضعیت</th><th>عمومی</th><th></th></tr></thead><tbody data-event-list></tbody></table></div></div></section></div>
</section><script src="/assets/marketing-workspace.js" defer></script>
<?php ProductShell::end(); ?>
