<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAdmin($core);$csrf=WebAction::csrfToken();
ProductShell::start($core,$user,'کمپین و رویداد','marketing','کمپین‌ها و رویدادها را آماده کن و موارد موردنظر را در منوی مهمان نمایش بده.',true);
?>
<section class="sc-workspace" data-marketing data-api="marketing/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>">
  <div class="sc-toolbar sc-local-nav"><div class="sc-tabs" role="tablist" aria-label="کمپین و رویداد"><button class="sc-tab" type="button" role="tab" aria-selected="true" data-tab="campaigns">کمپین‌ها</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="events">رویدادها</button></div></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال دریافت…</div>

  <section class="sc-work-panel sc-marketing-layout" data-panel="campaigns">
    <section class="sc-data-panel">
      <div class="sc-section-head"><div><h2>کمپین‌ها</h2><p>وضعیت، عنوان عمومی و زمان‌بندی کمپین‌ها را در یک فهرست ببین.</p></div></div>
      <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>نام</th><th>عنوان</th><th>وضعیت</th><th>عمومی</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-campaign-list></tbody></table></div>
    </section>
    <aside class="sc-card sc-marketing-editor"><form class="sc-card__body sc-form" data-campaign-form><div class="sc-section-title"><div><h2>کمپین</h2><p>کمپین تازه بساز یا مورد انتخاب‌شده را ویرایش کن.</p></div></div><input type="hidden" name="id" value="0"><label class="sc-field"><span class="sc-field__label">نام کمپین</span><input class="sc-control" name="name" required maxlength="160"></label><label class="sc-field"><span class="sc-field__label">عنوان مهمان</span><input class="sc-control" name="headline" required maxlength="200"></label><label class="sc-field"><span class="sc-field__label">متن</span><textarea class="sc-control" name="body" rows="3"></textarea></label><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">وضعیت</span><select class="sc-control" name="status"><option value="draft">پیش‌نویس</option><option value="scheduled">زمان‌بندی</option><option value="active">فعال</option><option value="paused">متوقف</option><option value="completed">تمام‌شده</option><option value="archived">آرشیو</option></select></label><label class="sc-field"><span class="sc-field__label">شروع</span><input class="sc-control" type="datetime-local" name="starts_at"></label><label class="sc-field"><span class="sc-field__label">پایان</span><input class="sc-control" type="datetime-local" name="ends_at"></label></div><label class="sc-check-line"><input type="checkbox" name="public_visible"> نمایش در منوی عمومی</label><div class="sc-actions"><button class="sc-button" type="submit">ذخیره کمپین</button><button class="sc-button sc-button--secondary" type="button" data-reset-campaign>کمپین تازه</button></div></form></aside>
  </section>

  <section class="sc-work-panel sc-marketing-layout" data-panel="events" hidden>
    <section class="sc-data-panel">
      <div class="sc-section-head"><div><h2>رویدادها</h2><p>زمان، وضعیت و نمایش عمومی رویدادهای مجموعه را مدیریت کن.</p></div></div>
      <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>عنوان</th><th>شروع</th><th>وضعیت</th><th>عمومی</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-event-list></tbody></table></div>
    </section>
    <aside class="sc-card sc-marketing-editor"><form class="sc-card__body sc-form" data-event-form><div class="sc-section-title"><div><h2>رویداد</h2><p>رویداد تازه بساز یا مورد انتخاب‌شده را ویرایش کن.</p></div></div><input type="hidden" name="id" value="0"><label class="sc-field"><span class="sc-field__label">عنوان</span><input class="sc-control" name="title" required maxlength="180"></label><label class="sc-field"><span class="sc-field__label">توضیح</span><textarea class="sc-control" name="description" rows="3"></textarea></label><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">وضعیت</span><select class="sc-control" name="status"><option value="draft">پیش‌نویس</option><option value="scheduled">زمان‌بندی</option><option value="active">فعال</option><option value="completed">تمام‌شده</option><option value="cancelled">لغوشده</option><option value="archived">آرشیو</option></select></label><label class="sc-field"><span class="sc-field__label">شروع</span><input class="sc-control" type="datetime-local" name="starts_at" required></label><label class="sc-field"><span class="sc-field__label">پایان</span><input class="sc-control" type="datetime-local" name="ends_at"></label><label class="sc-field"><span class="sc-field__label">ظرفیت</span><input class="sc-control" type="number" min="1" name="capacity"></label><label class="sc-field"><span class="sc-field__label">محل</span><input class="sc-control" name="location_label" maxlength="180"></label></div><label class="sc-check-line"><input type="checkbox" name="public_visible"> نمایش در منوی عمومی</label><div class="sc-actions"><button class="sc-button" type="submit">ذخیره رویداد</button><button class="sc-button sc-button--secondary" type="button" data-reset-event>رویداد تازه</button></div></form></aside>
  </section>
</section>
<script src="<?=ProductShell::asset('assets/marketing-workspace.js')?>" defer></script>
<?php ProductShell::end(); ?>
