-- M5.10 — canonical Settlement/Reconciliation owner.
-- Direct settlement is active here. Accommodation/Subscriber/Printing adapters remain later slices.

ALTER TABLE table_sessions
    ADD COLUMN discount_type VARCHAR(20) NULL,
    ADD COLUMN discount_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN discount_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN discount_by_user_id INT UNSIGNED NULL,
    ADD COLUMN discount_updated_at DATETIME NULL,
    ADD COLUMN checkout_subtotal BIGINT UNSIGNED NULL,
    ADD COLUMN checkout_discount BIGINT UNSIGNED NULL,
    ADD COLUMN checkout_total BIGINT UNSIGNED NULL,
    ADD COLUMN settlement_destination VARCHAR(30) NULL,
    ADD COLUMN checkout_voided_at DATETIME NULL,
    ADD COLUMN checkout_voided_by_user_id INT UNSIGNED NULL,
    ADD COLUMN closed_by_user_id INT UNSIGNED NULL,
    ADD COLUMN ended_reason VARCHAR(40) NULL,
    ADD CONSTRAINT fk_m510_session_discount_by FOREIGN KEY (discount_by_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD CONSTRAINT fk_m510_session_checkout_voided_by FOREIGN KEY (checkout_voided_by_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD CONSTRAINT fk_m510_session_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    ADD CONSTRAINT ck_m510_session_discount_type CHECK (discount_type IS NULL OR discount_type IN ('percent','fixed'));

CREATE TABLE IF NOT EXISTS settlement_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT UNSIGNED NOT NULL,
    financial_period_id INT UNSIGNED NOT NULL,
    invoice_number VARCHAR(40) NOT NULL,
    invoice_snapshot_json JSON NOT NULL,
    destination VARCHAR(30) NOT NULL,
    table_name_snapshot VARCHAR(160) NOT NULL,
    subtotal BIGINT UNSIGNED NOT NULL,
    discount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    taxable_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    tax_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    total BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    reverses_settlement_id BIGINT UNSIGNED NULL,
    actor_user_id INT UNSIGNED NULL,
    subscriber_ledger_entry_id BIGINT UNSIGNED NULL,
    accommodation_transfer_id BIGINT UNSIGNED NULL,
    final_print_job_id BIGINT UNSIGNED NULL,
    request_id VARCHAR(96) NULL,
    request_fingerprint CHAR(64) NULL,
    settlement_kind VARCHAR(20) NOT NULL DEFAULT 'full',
    closes_session TINYINT(1) NOT NULL DEFAULT 1,
    remaining_subtotal BIGINT UNSIGNED NOT NULL DEFAULT 0,
    remaining_discount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    remaining_tax BIGINT UNSIGNED NOT NULL DEFAULT 0,
    remaining_total BIGINT UNSIGNED NOT NULL DEFAULT 0,
    allocation_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    settled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    business_date DATE NOT NULL,
    business_shift_key VARCHAR(40) NOT NULL,
    business_shift_label VARCHAR(80) NOT NULL,
    business_cutoff_snapshot CHAR(5) NOT NULL,
    void_reason VARCHAR(300) NULL,
    voided_by_user_id INT UNSIGNED NULL,
    voided_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_m510_settlement_session FOREIGN KEY (session_id) REFERENCES table_sessions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_m510_settlement_period FOREIGN KEY (financial_period_id) REFERENCES financial_periods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_m510_settlement_reverses FOREIGN KEY (reverses_settlement_id) REFERENCES settlement_records(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_m510_settlement_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_m510_settlement_voided_by FOREIGN KEY (voided_by_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_m510_settlement_destination CHECK (destination IN ('direct','accommodation','subscriber')),
    CONSTRAINT ck_m510_settlement_status CHECK (status IN ('completed','reversal')),
    CONSTRAINT ck_m510_settlement_kind CHECK (settlement_kind IN ('full','itemized','reversal')),
    CONSTRAINT ck_m510_settlement_allocation CHECK (allocation_version IN (1,2)),
    UNIQUE KEY uq_settlement_invoice_number (invoice_number),
    UNIQUE KEY uq_settlement_reversal (reverses_settlement_id),
    UNIQUE KEY uq_settlement_request_id (request_id),
    INDEX idx_m510_settlement_period (financial_period_id,settled_at),
    INDEX idx_m510_settlement_session (session_id,settled_at),
    INDEX idx_m510_settlement_business (business_date,business_shift_key,status),
    INDEX idx_m510_settlement_destination (destination,settled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settlement_record_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    settlement_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NULL,
    order_id BIGINT UNSIGNED NULL,
    item_id_snapshot INT UNSIGNED NULL,
    item_name_snapshot VARCHAR(190) NOT NULL,
    unit_price_snapshot BIGINT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    gross_amount BIGINT UNSIGNED NOT NULL,
    discount_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    net_amount BIGINT UNSIGNED NOT NULL,
    taxable_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    tax_rate_bps SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    tax_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    final_amount BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_m510_settlement_line_record FOREIGN KEY (settlement_id) REFERENCES settlement_records(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE KEY uq_settlement_line_item (settlement_id,order_item_id),
    INDEX idx_m510_settlement_line_order_item (order_item_id),
    INDEX idx_m510_settlement_line_order (order_id),
    INDEX idx_m510_settlement_line_item_snapshot (item_id_snapshot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_discount_audit (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT UNSIGNED NOT NULL,
    previous_type VARCHAR(20) NULL,
    previous_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
    previous_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    new_type VARCHAR(20) NULL,
    new_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
    new_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    subtotal BIGINT UNSIGNED NOT NULL DEFAULT 0,
    actor_user_id INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_m510_discount_audit_session FOREIGN KEY (session_id) REFERENCES table_sessions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_m510_discount_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    INDEX idx_m510_discount_audit_session (session_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
