<?php
declare(strict_types=1);
use Sokna\Local\UI\LocalPage;use Sokna\Local\UI\ProductShell;use Sokna\Local\UI\WebAction;
$core=require dirname(__DIR__).'/_app.php';$user=LocalPage::requireAdmin($core);$csrf=WebAction::csrfToken();
ProductShell::start($core,$user,'مدیریت','admin','کاربران، پرسنل، تنظیمات عملیاتی، امکانات و میزها را از همین بخش مدیریت کن.',true);
?>
<section class="sc-workspace" data-admin-workspace data-api="admin/api.php" data-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8') ?>">
  <div class="sc-toolbar sc-local-nav"><div class="sc-tabs" role="tablist" aria-label="مدیریت"><button class="sc-tab" type="button" role="tab" aria-selected="true" data-tab="users">کاربران</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="personnel">پرسنل</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="settings">تنظیمات</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="modules">امکانات</button><button class="sc-tab" type="button" role="tab" aria-selected="false" data-tab="tables">میزها و QR</button></div><button class="sc-button sc-button--secondary" type="button" data-refresh>تازه‌سازی</button></div>
  <div class="sc-alert" role="status" aria-live="polite" data-status>در حال دریافت تنظیمات…</div>

  <section class="sc-work-panel sc-data-panel sc-management-panel" data-panel="users">
    <div class="sc-section-head"><div><h2>حساب‌های ورود</h2><p>حساب ورود با هویت پرسنلی یکی نیست؛ اتصال آن در بخش «پرسنل» اختیاری است.</p></div><button class="sc-button" type="button" data-open="user">حساب جدید</button></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>نام</th><th>نام کاربری</th><th>نقش</th><th>دسترسی‌ها</th><th>وضعیت</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-users></tbody></table></div>
  </section>

  <section class="sc-work-panel sc-data-panel sc-management-panel" data-panel="personnel" hidden>
    <div class="sc-section-head"><div><h2>پرسنل</h2><p>پرسنل می‌تواند بدون حساب ورود وجود داشته باشد. این هویت پایه برای مزایا، مصرف پرسنلی و حساب مستقل پرسنل است.</p></div><button class="sc-button" type="button" data-open="personnel">پرسنل جدید</button></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>نام</th><th>سمت</th><th>کد</th><th>حساب متصل</th><th>وضعیت</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-personnel></tbody></table></div>
  </section>

  <section class="sc-work-panel sc-data-panel sc-management-form-panel" data-panel="settings" hidden>
    <div class="sc-section-head"><div><h2>هویت و تنظیمات عملیاتی</h2><p>نام مجموعه، عنوان پنل و تنظیمات پایه‌ی روز کاری را از همین بخش مدیریت کن.</p></div></div>
    <form class="sc-card__body sc-form" data-settings-form><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">نام مجموعه</span><input class="sc-control" name="cafe_name" maxlength="120" required></label><label class="sc-field"><span class="sc-field__label">عنوان زیر نام مجموعه</span><input class="sc-control" name="brand_subtitle" maxlength="120" placeholder="مثلاً سامانه مدیریت کافه"></label></div><div class="sc-form-grid"><label class="sc-field"><span class="sc-field__label">شروع روز کاری</span><input class="sc-control" name="business_day_cutoff" type="time" required></label><label class="sc-field sc-toggle-field"><span class="sc-field__label">فراخوان همکار سالن</span><span><input type="checkbox" name="waiter_call_enabled"> فعال باشد</span></label></div><div class="sc-actions"><button class="sc-button" type="submit">ذخیره تنظیمات</button></div></form>
  </section>

  <section class="sc-work-panel sc-data-panel sc-management-modules-panel" data-panel="modules" hidden>
    <div class="sc-section-head"><div><h2>امکانات قابل مدیریت</h2><p>فقط قابلیت‌هایی که واقعاً در کار روزانه قابل تغییرند اینجا نمایش داده می‌شوند.</p></div></div><div class="sc-management-module-grid" data-modules></div>
  </section>

  <section class="sc-work-panel sc-data-panel sc-management-panel" data-panel="tables" hidden>
    <div class="sc-section-head"><div><h2>میزها و امنیت QR</h2><p>برای هر میز می‌توان QR تازه ساخت یا QR قبلی را دوباره فعال کرد.</p></div><div class="sc-actions"><button class="sc-button sc-button--secondary" type="button" data-open="bulk">ساخت گروهی</button><button class="sc-button" type="button" data-open="table">میز جدید</button></div></div>
    <div class="sc-table-wrap"><table class="sc-table sc-table--responsive"><thead><tr><th>میز</th><th>بخش</th><th>وضعیت</th><th>QR</th><th><span class="sc-visually-hidden">عملیات</span></th></tr></thead><tbody data-tables></tbody></table></div>
  </section>

  <dialog class="sc-dialog" data-dialog="user" aria-labelledby="sc-dialog-title-admin-user"><form method="dialog" class="sc-card__body sc-form" data-user-form><h2 data-user-title id="sc-dialog-title-admin-user">حساب کاربری</h2><input type="hidden" name="id"><label class="sc-field"><span class="sc-field__label">نام نمایشی</span><input class="sc-control" name="display_name" maxlength="120" required></label><label class="sc-field"><span class="sc-field__label">نام کاربری</span><input class="sc-control" name="username" maxlength="80" required autocomplete="off"></label><label class="sc-field"><span class="sc-field__label">رمز ورود محلی</span><input class="sc-control" name="password" type="password" minlength="8" autocomplete="new-password"><small>برای حساب موجود فقط در صورت تغییر رمز محلی پر شود.</small></label><label class="sc-field"><span class="sc-field__label">رمز دسترسی راه‌دور</span><input class="sc-control" name="remote_password" type="password" minlength="12" autocomplete="new-password"><small data-remote-credential-state>برای ورود اینترنتی، رمز جداگانه‌ای از رمز محلی تعیین می‌شود.</small></label><label class="sc-field"><span><input type="checkbox" name="remote_password_remove"> لغو رمز و ورود راه‌دور این حساب</span><small>برای لغو، «دسترسی راه‌دور» را هم از دسترسی‌های حساب بردار.</small></label><label class="sc-field"><span><input type="checkbox" name="active" checked> حساب فعال باشد</span></label><fieldset class="sc-field"><legend>دسترسی‌ها</legend><div class="sc-check-grid" data-capabilities></div></fieldset><fieldset class="sc-field"><legend>ناحیه آماده‌سازی</legend><label><input type="checkbox" name="preparation_areas" value="kitchen"> آشپزخانه</label><label><input type="checkbox" name="preparation_areas" value="bar"> بار</label></fieldset><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ذخیره</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="personnel" aria-labelledby="sc-dialog-title-admin-personnel"><form method="dialog" class="sc-card__body sc-form" data-personnel-form><h2 id="sc-dialog-title-admin-personnel">پرسنل</h2><input type="hidden" name="id"><label class="sc-field"><span class="sc-field__label">نام</span><input class="sc-control" name="display_name" maxlength="120" required></label><label class="sc-field"><span class="sc-field__label">سمت / عنوان</span><input class="sc-control" name="job_title" maxlength="120"></label><label class="sc-field"><span class="sc-field__label">کد پرسنلی (اختیاری)</span><input class="sc-control" name="personnel_code" maxlength="40"></label><label class="sc-field"><span class="sc-field__label">حساب ورود مرتبط (اختیاری)</span><select class="sc-control" name="linked_user_id" data-personnel-user><option value="0">بدون حساب ورود</option></select></label><label class="sc-field"><span class="sc-field__label">یادداشت</span><textarea class="sc-control" name="notes" maxlength="500"></textarea></label><label class="sc-field"><span><input type="checkbox" name="active" checked> پرسنل فعال باشد</span></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ذخیره</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="table" aria-labelledby="sc-dialog-title-admin-table"><form method="dialog" class="sc-card__body sc-form" data-table-form><h2 id="sc-dialog-title-admin-table">میز</h2><input type="hidden" name="id"><label class="sc-field"><span class="sc-field__label">نام میز</span><input class="sc-control" name="name" maxlength="100" required></label><label class="sc-field"><span class="sc-field__label">شماره میز</span><input class="sc-control" name="table_number" inputmode="numeric" required></label><label class="sc-field"><span class="sc-field__label">بخش / سالن</span><input class="sc-control" name="zone_label" maxlength="80"></label><label class="sc-field"><span><input type="checkbox" name="active" checked> میز فعال باشد</span></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ذخیره</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>

  <dialog class="sc-dialog" data-dialog="bulk" aria-labelledby="sc-dialog-title-admin-bulk"><form method="dialog" class="sc-card__body sc-form" data-bulk-form><h2 id="sc-dialog-title-admin-bulk">ساخت گروهی میز</h2><label class="sc-field"><span class="sc-field__label">از شماره</span><input class="sc-control" name="from_number" inputmode="numeric" required></label><label class="sc-field"><span class="sc-field__label">تا شماره</span><input class="sc-control" name="to_number" inputmode="numeric" required></label><label class="sc-field"><span class="sc-field__label">پیشوند نام</span><input class="sc-control" name="name_prefix" value="میز"></label><label class="sc-field"><span class="sc-field__label">بخش / سالن</span><input class="sc-control" name="zone_label" maxlength="80"></label><div class="sc-actions"><button class="sc-button" type="submit" value="submit">ساخت</button><button class="sc-button sc-button--secondary" type="button" data-dialog-close value="cancel">انصراف</button></div></form></dialog>
</section>
<script src="<?=ProductShell::asset('assets/admin-workspace.js')?>" defer></script>
<?php ProductShell::end(); ?>
